package org.bigbluebutton.presentation.handlers

import java.nio.ByteBuffer
import java.nio.charset.StandardCharsets
import java.nio.file.{ Files, Paths }

import org.bigbluebutton.api.util.UnitSpec

/**
 * Tests the tag-count parsing of SvgConversionHandler.
 *
 * During SVG slide analysis the conversion process runs
 *   grep -oE '<image|<path|<use|<mask' slideN.svg | sort | uniq -c
 * and the handler parses the resulting stdout. These tests replicate that
 * pipeline against src/test/resources/sample-with-mask.svg, which was
 * generated by pdftocairo 24.02.0 (Ubuntu 24.04) from
 * src/test/resources/sample-with-mask.pdf, a minimal PDF containing an
 * image XObject with an /SMask (soft mask) drawn twice - soft masks are
 * what pdftocairo turns into SVG <mask> elements.
 */
class SvgConversionHandlerTest extends UnitSpec {

  val sampleSvgFile = "src/test/resources/sample-with-mask.svg"
  val analyzedTags = List("<filter", "<image", "<mask", "<path", "<use")

  private def handlerFedWith(stdout: String): SvgConversionHandler = {
    val handler = new SvgConversionHandler("test")
    handler.onStdout(ByteBuffer.wrap(stdout.getBytes(StandardCharsets.UTF_8)), true)
    handler
  }

  private def countOccurrences(content: String, token: String): Int = {
    var count = 0
    var idx = content.indexOf(token)
    while (idx > -1) {
      count += 1
      idx = content.indexOf(token, idx + token.length)
    }
    count
  }

  // Replicates the analysis pipeline: grep -oE '<image|<path|<use|<mask' | sort | uniq -c
  private def uniqCountOutput(content: String): String = {
    analyzedTags.map(tag => "%7d %s\n".format(countOccurrences(content, tag), tag)).mkString
  }

  it should "count mask tags from the analysis output of a generated svg with soft masks" in {
    val svgContent = new String(Files.readAllBytes(Paths.get(sampleSvgFile)), StandardCharsets.UTF_8)
    val handler = handlerFedWith(uniqCountOutput(svgContent))

    assert(handler.numberOfMaskTags() == countOccurrences(svgContent, "<mask"))
    assert(handler.numberOfMaskTags() == 2)
    assert(handler.numberOfImageTags() == 3)
    assert(handler.numberOfPaths() == 2)
    assert(handler.numberOfUseTags() == 4)
    assert(handler.numberOfFilterTags() == countOccurrences(svgContent, "<filter"))
  }

  it should "count zero mask tags when the analysis output has no mask line" in {
    val handler = handlerFedWith("      2 <image\n    159 <path\n    444 <use\n")

    assert(handler.numberOfMaskTags() == 0)
    assert(handler.numberOfImageTags() == 2)
    assert(handler.numberOfPaths() == 159)
    assert(handler.numberOfUseTags() == 444)
  }

  it should "count zero tags when the analysis output is not uniq -c formatted" in {
    val handler = handlerFedWith("pdftocairo: unknown error\n")

    assert(handler.numberOfMaskTags() == 0)
    assert(handler.numberOfImageTags() == 0)
    assert(handler.numberOfPaths() == 0)
    assert(handler.numberOfUseTags() == 0)
  }

}
