// GLOBAL TESTS VARS
exports.TEST_DURATION_TIME = 3600000;
exports.USER_LIST_VLIST_BOTS_TALKING = 1;
exports.USER_LIST_VLIST_BOTS_LISTENING = 100;
exports.LOOP_INTERVAL = 1200;
exports.ELEMENT_WAIT_TIME = 5000;
exports.ELEMENT_WAIT_LONGER_TIME = 10000;
exports.CLIENT_RECONNECTION_TIMEOUT = 120000;

// STRESS TESTS VARS
exports.JOIN_AS_MODERATOR_TEST_ROUNDS = 100;
exports.MAX_JOIN_AS_MODERATOR_FAIL_RATE = 0.05;
exports.BREAKOUT_ROOM_INVITATION_TEST_ROUNDS = 20;

// MEDIA CONNECTION TIMEOUTS
exports.VIDEO_LOADING_WAIT_TIME = 15000;
exports.LISTEN_ONLY_WAIT_TIME = 25000;
exports.VIDEO_PREVIEW_TIMEOUT = 20000;
exports.UPLOAD_PDF_WAIT_TIME = 20000;

// TESTS TIMEOUTS
exports.MAX_AUDIO_TEST_TIMEOUT = 50000;
exports.MAX_BREAKOUT_TEST_TIMEOUT = 150000;
exports.MAX_CHAT_TEST_TIMEOUT = 50000;
exports.MAX_CUSTOM_PARAMETERS_TEST_TIMEOUT = 50000;
exports.MAX_NOTIFICATIONS_TEST_TIMEOUT = 80000;
exports.MAX_POLLING_TEST_TIMEOUT = 50000;
exports.MAX_PRESENTATION_TEST_TIMEOUT = 50000;
exports.MAX_SCREENSHARE_TEST_TIMEOUT = 30000;
exports.MAX_SHARED_NOTES_TEST_TIMEOUT = 30000;
exports.MAX_MULTIUSERS_TEST_TIMEOUT = 30000;
exports.MAX_WEBCAM_TEST_TIMEOUT = 50000;
exports.MAX_WEBCAM_LAYOUT_TEST_TIMEOUT = 80000;
exports.MAX_WHITEBOARD_TEST_TIMEOUT = 80000;
exports.MAX_TRIGGER_EVENTS_TEST_TIMEOUT = 200000;
