import { AudioPresets, LogLevel } from 'livekit-client';
import { MeetingClientSettings } from '../../Types/meetingClientSettings';

export const meetingClientSettingsInitialValues: MeetingClientSettings = {
  public: {
    app: {
      terminateAndRetryConnection: 30000,
      mobileFontSize: '16px',
      desktopFontSize: '14px',
      autoJoin: true,
      listenOnlyMode: true,
      forceListenOnly: false,
      skipCheck: false,
      skipCheckOnJoin: false,
      enableDynamicAudioDeviceSelection: true,
      skipEchoTestIfPreviousDevice: false,
      clientTitle: 'BigBlueButton',
      bbbServerVersion: 'HTML5_FULL_BBB_VERSION',
      displayBbbServerVersion: true,
      copyright: '©2026 BigBlueButton Inc.',
      html5ClientBuild: 'HTML5_CLIENT_VERSION',
      helpLink: 'https://bigbluebutton.org/html5/',
      delayForUnmountOfSharedNote: 120000,
      enableApolloDevTools: false,
      bbbTabletApp: {
        enabled: true,
        iosAppStoreUrl: 'https://apps.apple.com/us/app/bigbluebutton-tablet/id1641156756',
        iosAppUrlScheme: 'bigbluebutton-tablet',
      },
      cdn: '',
      basename: '/html5client',
      bbbWebBase: '/bigbluebutton',
      learningDashboardBase: '/learning-analytics-dashboard',
      customStyleUrl: null,
      darkTheme: {
        enabled: true,
        autoDetectFromSystem: true,
      },
      askForConfirmationOnLeave: true,
      wakeLock: {
        enabled: true,
      },
      allowDefaultLogoutUrl: true,
      skipMeetingEnded: false,
      dynamicGuestPolicy: true,
      enableGuestLobbyMessage: true,
      showGuestLobbyWaitingQueuePosition: true,
      guestPolicyExtraAllowOptions: false,
      alwaysShowWaitingRoomUI: true,
      enableLimitOfViewersInWebcam: false,
      enableMultipleCameras: true,
      enableCameraAsContent: true,
      enableWebcamSelectorButton: true,
      enableTalkingIndicator: true,
      enableCameraBrightness: true,
      mirrorOwnWebcam: true,
      viewersInWebcam: 8,
      allowLogout: true,
      allowFullscreen: true,
      preloadNextSlides: 2,
      warnAboutUnsavedContentOnMeetingEnd: false,
      audioCaptions: {
        alwaysVisible: false,
        enabled: false,
        mobile: false,
        provider: 'webspeech',
        showInSidebarNavigation: false,
        microphoneAlert: {
          enabled: true,
          helpLink: '',
          threshold: -50,
          speakingThreshold: 5000,
          duration: 10000,
          interval: 200,
        },
        language: {
          available: [
            'en-US',
            'es-ES',
            'fr-FR',
            'pt-BR',
          ],
          forceLocale: false,
          defaultSelectLocale: true,
          locale: 'disabled',
        },
        terms: {},
      },
      mutedAlert: {
        enabled: true,
        interval: 200,
        threshold: -50,
        duration: 4000,
      },
      appsGallery: {
        maxPinnedApps: 3,
      },
      remainingTimeAlertThresholdArray: [
        1,
        5,
      ],
      enableDebugWindow: true,
      breakouts: {
        allowUserChooseRoomByDefault: false,
        offerRecordingForBreakouts: false,
        recordRoomByDefault: false,
        captureWhiteboardByDefault: false,
        captureSharedNotesByDefault: false,
        sendInvitationToAssignedModeratorsByDefault: false,
        breakoutRoomMinimum: 2,
        breakoutRoomLimit: 16,
        allowPresentationManagementInBreakouts: true,
        lockBreakoutRecordingSetting: false,
      },
      showAllAvailableLocales: true,
      showAudioFilters: true,
      reactionsButton: {
        enabled: true,
      },
      emojiRain: {
        enabled: false,
        intervalEmojis: 2000,
        numberOfEmojis: 5,
        emojiSize: 2,
      },
      enableNetworkStats: true,
      enableCopyNetworkStatsButton: true,
      userSettingsStorage: 'session',
      defaultSettings: {
        layout: {
          selectedLayout: 'unified',
          pushLayout: false,
        },
        application: {
          animations: true,
          chatAudioAlerts: false,
          chatPushAlerts: false,
          userJoinAudioAlerts: false,
          userJoinPushAlerts: false,
          userLeaveAudioAlerts: false,
          userLeavePushAlerts: false,
          raiseHandAudioAlerts: true,
          raiseHandPushAlerts: true,
          guestWaitingAudioAlerts: true,
          guestWaitingPushAlerts: true,
          muteUnmuteAudioAlerts: true,
          wakeLock: true,
          paginationEnabled: true,
          whiteboardToolbarAutoHide: false,
          pushToTalkEnabled: false,
          autoCloseReactionsBar: true,
          directLeaveButton: true,
          darkTheme: false,
          webcamBorderHighlightColor: [],
          fallbackLocale: 'en',
          overrideLocale: null,
          audioWasmProcessing: true,
        },
        audio: {
          inputDeviceId: 'undefined',
          outputDeviceId: 'undefined',
        },
        dataSaving: {
          viewParticipantsWebcams: true,
          viewScreenshare: true,
        },
        transcription: {
          partialUtterances: true,
          minUtteranceLength: 1,
        },
      },
      shortcuts: {
        openOptions: {
          accesskey: 'O',
          descId: 'openOptions',
        },
        toggleUserList: {
          accesskey: 'U',
          descId: 'toggleUserList',
        },
        openLeaveMenu: {
          accesskey: 'X',
          descId: 'openLeaveMenu',
        },
        toggleMute: {
          accesskey: 'M',
          descId: 'toggleMute',
        },
        joinAudio: {
          accesskey: 'J',
          descId: 'joinAudio',
        },
        leaveAudio: {
          accesskey: 'L',
          descId: 'leaveAudio',
        },
        togglePublicChat: {
          accesskey: 'P',
          descId: 'togglePublicChat',
        },
        hidePrivateChat: {
          accesskey: 'H',
          descId: 'hidePrivateChat',
        },
        closePrivateChat: {
          accesskey: 'G',
          descId: 'closePrivateChat',
        },
        raiseHand: {
          accesskey: 'R',
          descId: 'raiseHand',
        },
        openActions: {
          accesskey: 'A',
          descId: 'openActions',
        },
        openDebugWindow: {
          accesskey: 'K',
          descId: 'openDebugWindow',
        },
      },
      branding: {
        displayBrandingArea: true,
      },
      connectionTimeout: 60000,
      showHelpButton: true,
      fallbackOnEmptyLocaleString: true,
      maxMutationPayloadSize: 10485760, // 10MB
      timeoutBeforeRedirectOnMeetingEnd: 20000,
      showConnectionErrors: [3002, 3004],
    },
    sharedNotes: {
      serverHostname: '',
      maxDocumentChars: 99999,
      maxLengthForContentUpdate: 1500,
      staticFormattingToolbar: true,
      importMarkdownEnabled: false,
      exportMarkdownEnabled: false,
    },
    externalVideoPlayer: {
      enabled: true,
    },
    kurento: {
      wsUrl: 'HOST',
      cameraWsOptions: {
        connectionTimeout: 4000,
        maxRetries: 7,
        debug: false,
        heartbeat: {
          interval: 15000,
          delay: 3000,
          reconnectOnFailure: true,
        },
      },
      gUMTimeout: 20000,
      signalCandidates: false,
      restartIce: {
        audio: {
          enabled: false,
          retries: 1,
        },
        video: {
          enabled: false,
          retries: 3,
        },
        screenshare: {
          enabled: false,
          retries: 3,
        },
      },
      traceLogs: false,
      cameraTimeouts: {
        baseTimeout: 30000,
        maxTimeout: 60000,
      },
      screenshare: {
        showButtonForNonPresenters: false,
        enableVolumeControl: true,
        subscriberOffering: false,
        bitrate: 1500,
        mediaTimeouts: {
          maxConnectionAttempts: 2,
          baseTimeout: 20000,
          baseReconnectionTimeout: 8000,
          maxTimeout: 25000,
          timeoutIncreaseFactor: 1.5,
        },
        constraints: {
          video: {
            frameRate: {
              ideal: 5,
              max: 10,
            },
            width: {
              max: 2560,
            },
            height: {
              max: 1600,
            },
          },
          audio: true,
        },
      },
      cameraProfiles: [
        {
          id: 'low-u30',
          name: 'low-u30',
          bitrate: 30,
          hidden: true,
        },
        {
          id: 'low-u25',
          name: 'low-u25',
          bitrate: 40,
          hidden: true,
        },
        {
          id: 'low-u20',
          name: 'low-u20',
          bitrate: 50,
          hidden: true,
        },
        {
          id: 'low-u15',
          name: 'low-u15',
          bitrate: 70,
          hidden: true,
        },
        {
          id: 'low-u12',
          name: 'low-u12',
          bitrate: 90,
          hidden: true,
        },
        {
          id: 'low-u8',
          name: 'low-u8',
          bitrate: 100,
          hidden: true,
        },
        {
          id: 'low',
          name: 'Low',
          default: false,
          bitrate: 100,
        },
        {
          id: 'medium',
          name: 'Medium',
          default: true,
          bitrate: 200,
        },
        {
          id: 'high',
          name: 'High',
          default: false,
          bitrate: 500,
          constraints: {
            width: 1280,
            height: 720,
            frameRate: 15,
          },
        },
        {
          id: 'hd',
          name: 'High definition',
          default: false,
          bitrate: 800,
          constraints: {
            width: 1280,
            height: 720,
            frameRate: 30,
          },
        },
        {
          id: 'fhd',
          name: 'Camera as content',
          hidden: true,
          default: false,
          bitrate: 1500,
          constraints: {
            width: 1920,
            height: 1080,
          },
        },
      ],
      enableScreensharing: true,
      enableVideo: true,
      enableVideoMenu: true,
      enableVideoPin: true,
      autoShareWebcam: false,
      skipVideoPreview: false,
      skipVideoPreviewOnFirstJoin: false,
      skipVideoPreviewIfPreviousDevice: false,
      cameraSortingModes: {
        defaultSorting: 'LOCAL_ALPHABETICAL',
        paginationSorting: 'VOICE_ACTIVITY_LOCAL',
        showAudioOnlyOnFirstPage: true,
        maxAudioOnlyUsers: 2,
        partitionPrivilegedStreams: true,
      },
      cameraQualityThresholds: {
        enabled: true,
        applyConstraints: false,
        privilegedStreams: true,
        debounceTime: 2500,
        thresholds: [
          {
            threshold: 8,
            profile: 'low-u8',
          },
          {
            threshold: 12,
            profile: 'low-u12',
          },
          {
            threshold: 15,
            profile: 'low-u15',
          },
          {
            threshold: 20,
            profile: 'low-u20',
          },
          {
            threshold: 25,
            profile: 'low-u25',
          },
          {
            threshold: 30,
            profile: 'low-u30',
          },
        ],
      },
      pagination: {
        paginationToggleEnabled: true,
        pageChangeDebounceTime: 1000,
        desktopPageSizes: {
          moderator: 0,
          viewer: 5,
        },
        mobilePageSizes: {
          moderator: 2,
          viewer: 2,
        },
        desktopGridSizes: {
          moderator: 48,
          viewer: 48,
        },
        mobileGridSizes: {
          moderator: 14,
          viewer: 14,
        },
      },
      paginationThresholds: {
        enabled: false,
        thresholds: [
          {
            users: 30,
            desktopPageSizes: {
              moderator: 25,
              viewer: 25,
            },
          },
          {
            users: 40,
            desktopPageSizes: {
              moderator: 20,
              viewer: 20,
            },
          },
          {
            users: 50,
            desktopPageSizes: {
              moderator: 16,
              viewer: 16,
            },
          },
          {
            users: 60,
            desktopPageSizes: {
              moderator: 14,
              viewer: 12,
            },
          },
          {
            users: 70,
            desktopPageSizes: {
              moderator: 12,
              viewer: 10,
            },
          },
          {
            users: 80,
            desktopPageSizes: {
              moderator: 10,
              viewer: 8,
            },
          },
          {
            users: 90,
            desktopPageSizes: {
              moderator: 8,
              viewer: 6,
            },
          },
          {
            users: 100,
            desktopPageSizes: {
              moderator: 6,
              viewer: 4,
            },
          },
        ],
      },
    },
    poll: {
      enabled: true,
      allowCustomResponseInput: true,
      maxCustom: 5,
      maxTypedAnswerLength: 45,
      chatMessage: true,
      quickPollConfirmationStep: true,
      quiz: {
        enabled: true,
        quickPollCorrectAnswerSuffix: '__',
      },
    },
    captions: {
      background: '#000000',
      font: {
        color: '#ffffff',
        family: 'Calibri',
        size: '24px',
      },
      locales: [
        { locale: 'af', name: 'Afrikaans' },
        { locale: 'ar', name: 'العربية' },
        { locale: 'az', name: 'Azərbaycan dili' },
        { locale: 'bg-BG', name: 'Български' },
        { locale: 'bn', name: 'বাংলা' },
        { locale: 'ca', name: 'Català' },
        { locale: 'cs-CZ', name: 'Čeština' },
        { locale: 'da', name: 'Dansk' },
        { locale: 'de', name: 'Deutsch' },
        { locale: 'dv', name: 'ދިވެހި' },
        { locale: 'el-GR', name: 'Ελληνικά' },
        { locale: 'en', name: 'English' },
        { locale: 'en-US', name: 'English' },
        { locale: 'eo', name: 'Esperanto' },
        { locale: 'es', name: 'Español' },
        { locale: 'es-419', name: 'Español (Latinoamérica)' },
        { locale: 'es-ES', name: 'Español (España)' },
        { locale: 'es-MX', name: 'Español (México)' },
        { locale: 'et', name: 'eesti keel' },
        { locale: 'eu', name: 'Euskara' },
        { locale: 'fa-IR', name: 'فارسی' },
        { locale: 'fi', name: 'Suomi' },
        { locale: 'fr', name: 'Français' },
        { locale: 'gl', name: 'Galego' },
        { locale: 'he', name: 'עברית‏' },
        { locale: 'hi-IN', name: 'हिन्दी' },
        { locale: 'hr', name: 'Hrvatski' },
        { locale: 'hu-HU', name: 'Magyar' },
        { locale: 'hy', name: 'Հայերեն' },
        { locale: 'id', name: 'Bahasa Indonesia' },
        { locale: 'it-IT', name: 'Italiano' },
        { locale: 'ja', name: '日本語' },
        { locale: 'ka', name: 'ქართული' },
        { locale: 'km', name: 'ភាសាខ្មែរ' },
        { locale: 'kn', name: 'ಕನ್ನಡ' },
        { locale: 'ko-KR', name: '한국어 (韩国)' },
        { locale: 'lo-LA', name: 'ລາວ' },
        { locale: 'lt-LT', name: 'Lietuvių' },
        { locale: 'lv', name: 'Latviešu' },
        { locale: 'ml', name: 'മലയാളം' },
        { locale: 'mn-MN', name: 'Монгол' },
        { locale: 'nb-NO', name: 'Norsk (bokmål)' },
        { locale: 'nl', name: 'Nederlands' },
        { locale: 'oc', name: 'Occitan' },
        { locale: 'pl-PL', name: 'Polski' },
        { locale: 'pt', name: 'Português' },
        { locale: 'pt-BR', name: 'Português (Brasil)' },
        { locale: 'ro-RO', name: 'Română' },
        { locale: 'ru', name: 'Русский' },
        { locale: 'sk-SK', name: 'Slovenčina (Slovakia)' },
        { locale: 'sl', name: 'Slovenščina' },
        { locale: 'sr', name: 'Српски' },
        { locale: 'sv-SE', name: 'Svenska' },
        { locale: 'ta', name: 'தமிழ்' },
        { locale: 'te', name: 'తెలుగు' },
        { locale: 'th', name: 'ภาษาไทย' },
        { locale: 'tr-TR', name: 'Türkçe' },
        { locale: 'uk-UA', name: 'Українська' },
        { locale: 'vi-VN', name: 'Tiếng Việt' },
        { locale: 'zh-CN', name: '中文（中国' },
        { locale: 'zh-TW', name: '中文（台灣' },
      ],
      lines: 2,
      time: 5000,
      captionLimit: 3,
      lineLimit: 60,
    },
    timer: {
      enabled: true,
      time: 5,
      music: {
        enabled: false,
        volume: 0.4,
        track1: 'RelaxingMusic',
        track2: 'CalmMusic',
        track3: 'aristocratDrums',
      },
      maxHours: 23,
      presets: [60, 300, 600, 900, 1200, 1800, 3600],
      quickAddButtons: [30, 60, 300],
      serverSyncTimeInterval: 300000, // 5 minutes
    },
    chat: {
      enabled: true,
      itemsPerPage: 100,
      enableSaveAndCopyPublicChat: true,
      startClosed: false,
      min_message_length: 1,
      max_message_length: 5000,
      type_system: 'SYSTEM_MESSAGE',
      type_public: 'PUBLIC_ACCESS',
      type_private: 'PRIVATE_ACCESS',
      system_userid: 'SYSTEM_MESSAGE',
      system_username: 'SYSTEM_MESSAGE',
      public_id: 'public',
      public_group_id: 'MAIN-PUBLIC-GROUP-CHAT',
      public_userid: 'public_chat_userid',
      public_username: 'public_chat_username',
      storage_key: 'UNREAD_CHATS',
      system_messages_keys: {
        chat_clear: 'PUBLIC_CHAT_CLEAR',
        chat_poll_result: 'PUBLIC_CHAT_POLL_RESULT',
        chat_exported_presentation: 'PUBLIC_CHAT_EXPORTED_PRESENTATION',
        chat_status_message: 'PUBLIC_CHAT_STATUS',
      },
      typingIndicator: {
        enabled: true,
        showNames: true,
      },
      moderatorChatEmphasized: true,
      privateMessageReadFeedback: {
        enabled: false,
      },
      autoConvertEmoji: true,
      emojiPicker: {
        enable: false,
      },
      disableEmojis: [],
      markdownImageAllowed: false,
      toolbar: ['reply', 'delete', 'edit', 'reactions', 'pin'],
      announcePresenterChangeInChat: true,
    },
    userReaction: {
      enabled: true,
      expire: 30,
      reactions: [
        {
          id: 'smiley',
          native: '😃',
        },
        {
          id: 'neutral_face',
          native: '😐',
        },
        {
          id: 'slightly_frowning_face',
          native: '🙁',
        },
        {
          id: '-1',
          native: '👎',
        },
        {
          id: '+1',
          native: '👍',
        },
        {
          id: 'clap',
          native: '👏',
        },
      ],
    },
    multiFunctionalMode: {
      enabled: false,
    },
    notes: {
      enabled: true,
      id: 'notes',
      pinnable: true,
    },
    layout: {
      hidePresentationOnJoin: false,
      showParticipantsOnLogin: false,
      showSessionDetailsOnJoin: true,
      showScreenshareQuickSwapButton: false,
      showLeaveSessionLabel: false,
      usersPerUserListPage: 50,
      syncCameraDockSizeAndPosition: true,
    },
    sidebarNavigation: {
      appsToLabelAsNew: [],
      buttons: {
        top: ['profile', 'user-list', 'chat', 'notes'],
        center: ['apps-gallery', 'pinned-apps'],
        bottom: ['audio-captions', 'learning-dashboard', 'settings'],
      },
    },
    pads: {
      url: 'ETHERPAD_HOST',
    },
    media: {
      audio: {
        defaultFullAudioBridge: 'livekit',
        defaultListenOnlyBridge: 'livekit',
        retryThroughRelay: false,
        allowAudioJoinCancel: true,
        audioWasmProcessing: {
          enabled: false,
          constraints: {
            echoCancellation: true,
            autoGainControl: true,
            noiseSuppression: true,
          },
        },
      },
      stunTurnServersFetchAddress: '/bigbluebutton/api/stuns',
      cacheStunTurnServers: true,
      fallbackStunServer: '',
      forceRelay: false,
      forceRelayOnFirefox: true,
      mediaTag: '#remote-media',
      echoTestNumber: 'echo',
      listenOnlyCallTimeout: 15000,
      transparentListenOnly: true,
      fullAudioOffering: true,
      listenOnlyOffering: false,
      toggleMuteThrottleTime: 300,
      localEchoTest: {
        enabled: true,
        initialHearingState: true,
        useRtcLoopbackInChromium: true,
        delay: {
          enabled: true,
          delayTime: 0.5,
          maxDelayTime: 2,
        },
      },
      networkPriorities: {
        audio: 'high',
        webcam: 'medium',
        screenshare: 'medium',
      },
      muteAudioOutputWhenAway: false,
      skipInitialCamEnumeration: false,
      screenshareTroubleshootingLinks: {
        1136: 'https://support.bigbluebutton.org/hc/en-us/articles/1500005316582-Share-my-screen#:~:text=Error%201136%3A%20Permission%20to%20capture,able%20to%20screen%20share%20again',
      },
      screenshare: {
        showButtonForNonPresenters: false,
      },
      livekit: {
        url: `wss://${window.location.hostname}/livekit`,
        selectiveSubscription: {
          enabled: true,
          audioSubscriptionPoolSize: 0,
          muteDebounceMs: 2500,
        },
        logLevel: LogLevel.warn,
        reconnectOnFatalFailures: true,
        forceRelay: false,
        forceRelayOnFirefox: false,
        roomOptions: {
          adaptiveStream: true,
          dynacast: true,
          stopLocalTrackOnUnpublish: false,
          singlePeerConnection: false,
        },
        audio: {
          publishOptions: {
            audioPreset: {
              ...AudioPresets.music,
              priority: 'high',
            },
            dtx: false,
            red: true,
            forceStereo: false,
          },
          unpublishOnMute: true,
          unpublishAfterMuteMs: 5000,
          useLiveKitAudioState: false,
        },
        camera: {
          publishOptions: {
            videoCodec: 'vp8',
          },
        },
        screenshare: {
          publishOptions: {
            videoCodec: 'vp8',
          },
          constraints: {
            video: {
              frameRate: {
                ideal: 15,
                max: 15,
              },
              width: {
                max: 2560,
              },
              height: {
                max: 1600,
              },
            },
            audio: true,
          },
          presets: [
            {
              maxBitrate: 500000,
              maxFramerate: 5,
              priority: 'medium',
            },
            {
              maxBitrate: 1500000,
              maxFramerate: 15,
              priority: 'medium',
            },
          ],
        },
      },
    },
    stats: {
      enabled: true,
      interval: 10000,
      probes: 5,
      timeout: 10000,
      logMediaStats: {
        enabled: false,
        additionalStatsTypes: {
          common: [],
          audio: [],
          video: [],
          screenshare: [],
        },
      },
      notification: {
        warning: false,
        error: true,
      },
      loss: {
        warning: 0.05,
        danger: 0.1,
        critical: 0.2,
      },
      rtt: {
        warning: 500,
        danger: 1000,
        critical: 2000,
      },
      help: 'STATS_HELP_URL',
    },
    presentation: {
      allowDownloadOriginal: true,
      allowDownloadWithAnnotations: true,
      allowSnapshotOfCurrentSlide: true,
      panZoomThrottle: 32,
      restoreOnUpdate: true,
      uploadEndpoint: '/bigbluebutton/presentation/upload',
      fileUploadConstraintsHint: false,
      mirroredFromBBBCore: {
        uploadSizeMax: 30000000,
        uploadPagesMax: 200,
      },
      uploadValidMimeTypes: [
        {
          extension: '.pdf',
          mime: 'application/pdf',
        },
        {
          extension: '.doc',
          mime: 'application/msword',
        },
        {
          extension: '.docx',
          mime: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        },
        {
          extension: '.xls',
          mime: 'application/vnd.ms-excel',
        },
        {
          extension: '.xlsx',
          mime: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        },
        {
          extension: '.ppt',
          mime: 'application/vnd.ms-powerpoint',
        },
        {
          extension: '.pptx',
          mime: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        },
        {
          extension: '.txt',
          mime: 'text/plain',
        },
        {
          extension: '.rtf',
          mime: 'application/rtf',
        },
        {
          extension: '.odt',
          mime: 'application/vnd.oasis.opendocument.text',
        },
        {
          extension: '.ods',
          mime: 'application/vnd.oasis.opendocument.spreadsheet',
        },
        {
          extension: '.odp',
          mime: 'application/vnd.oasis.opendocument.presentation',
        },
        {
          extension: '.odg',
          mime: 'application/vnd.oasis.opendocument.graphics',
        },
        {
          extension: '.jpg',
          mime: 'image/jpeg',
        },
        {
          extension: '.jpeg',
          mime: 'image/jpeg',
        },
        {
          extension: '.png',
          mime: 'image/png',
        },
        {
          extension: '.webp',
          mime: 'image/webp',
        },
      ],
    },
    user: {
      role_moderator: 'MODERATOR',
      role_viewer: 'VIEWER',
      label: {
        presenter: true,
        moderator: true,
        mobile: true,
        guest: true,
        sharingWebcam: true,
        bot: true,
      },
    },
    userList: {
      searchBar: {
        enabled: true,
      },
    },
    whiteboard: {
      annotationsQueueProcessInterval: 60,
      cursorInterval: 100,
      pointerDiameter: 5,
      maxStickyNoteLength: 1000,
      maxNumberOfAnnotations: 300,
      maxNumberOfActiveUsers: 25,
      maxHistoryStackSize: 400,
      lockToolbarTools: false,
      allowInfiniteWhiteboard: false,
      allowInfiniteWhiteboardInBreakouts: false,
      allowInfiniteWhiteboardPanForViewers: false,
      locales: [
        'ar', 'ca', 'cs', 'da', 'de', 'en', 'es', 'fa', 'fi', 'fr', 'gl', 'he',
        'hi-in', 'hu', 'it', 'ja', 'ko-kr', 'ku', 'main', 'my', 'ne', 'no',
        'pl', 'pt-br', 'pt-pt', 'ro', 'ru', 'sv', 'te', 'th', 'tr', 'uk',
        'vi', 'zh-cn', 'zh-tw',
      ],
      annotations: {
        status: {
          start: 'DRAW_START',
          update: 'DRAW_UPDATE',
          end: 'DRAW_END',
        },
      },
      styles: {
        colorStyle: 'black',
        dashStyle: 'draw',
        fillStyle: 'none',
        fontStyle: 'draw',
        sizeStyle: 'm',
        text: {
          family: 'script',
        },
      },
      toolbar: {
        multiUserPenOnly: false,
        initialSelectedTool: 'draw',
        presenterTools: [
          'select',
          'hand',
          'draw',
          'eraser',
          'arrow',
          'text',
          'note',
          'rectangle',
          'delete-selected-items',
          'highlight',
          'more',
          'actions',
          'ellipse',
          'diamond',
          'triangle',
          'trapezoid',
          'rhombus',
          'hexagon',
          'cloud',
          'star',
          'oval',
          'x-box',
          'check-box',
          'arrow-left',
          'arrow-up',
          'arrow-down',
          'arrow-right',
          'line',
          'frame',
        ],
        multiUserTools: [
          'select',
          'hand',
          'draw',
          'eraser',
          'arrow',
          'text',
          'note',
          'rectangle',
          'delete-selected-items',
          'highlight',
          'more',
          'actions',
          'ellipse',
          'diamond',
          'triangle',
          'trapezoid',
          'rhombus',
          'hexagon',
          'cloud',
          'star',
          'oval',
          'x-box',
          'check-box',
          'arrow-left',
          'arrow-up',
          'arrow-down',
          'arrow-right',
          'line',
          'frame',
        ],
      },
    },
    clientLog: {
      console: {
        enableRuntimeErrorLogging: false,
        enabled: true,
        level: 'debug',
      },
      external: {
        enabled: false,
        level: 'info',
        url: 'https://LOG_HOST/html5Log',
        method: 'POST',
        throttleInterval: 400,
        flushOnClose: true,
        logTag: '',
      },
    },
    virtualBackgrounds: {
      enabled: true,
      enableVirtualBackgroundUpload: true,
      storedOnBBB: true,
      showThumbnails: true,
      imagesPath: '/resources/images/virtual-backgrounds/',
      thumbnailsPath: '/resources/images/virtual-backgrounds/thumbnails/',
      fileNames: [
        'home.jpg',
        'coffeeshop.jpg',
        'board.jpg',
      ],
    },
  },
  private: {
    analytics: {},
    app: {
      host: '127.0.0.1',
      localesUrl: '/locale-list',
    },
  },
};

export default meetingClientSettingsInitialValues;
