#
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/
#
# Copyright (c) 2012 BigBlueButton Inc. and by respective authors (see below).
#
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
#


source "http://rubygems.org"

gem "rspec", "2.0.0", :require => "spec"
gem "cucumber", "0.9.2"
gem "redis", "2.1.1"
#gem "SystemTimer", "1.2.3"
gem "nokogiri", "1.4.4"
gem "resque", "1.15.0"
gem "mime-types"
gem "streamio-ffmpeg"
gem "rubyzip"
gem "curb"
gem "builder"
gem "trollop"
gem "open4"
