services:
  akka-bbb-apps:
    image: "${IMAGE_REPO:-bigbluebutton}/akka-bbb-apps:${IMAGE_AKKA_BBB_APPS_TAG:-latest}"
    build:
      context: "./akka-bbb-apps"
  html5-client:
    image: "${IMAGE_REPO:-bigbluebutton}/html5-client:${IMAGE_HTML5_CLIENT_TAG:-latest}"
    build:
      context: "./bigbluebutton-html5"
  learning-dashboard:
    image: "${IMAGE_REPO:-bigbluebutton}/learning-dashboard:${IMAGE_LEARNING_DASHBOARD_TAG:-latest}"
    build:
      context: "./bbb-learning-dashboard"
  graphql-actions:
    image: "${IMAGE_REPO:-bigbluebutton}/graphql-actions:${IMAGE_GRAPHQL_ACTIONS_TAG:-latest}"
    build:
      context: "./bbb-graphql-actions"
  graphql-middleware:
    image: "${IMAGE_REPO:-bigbluebutton}/graphql-middleware:${IMAGE_GRAPHQL_MIDDLEWARE_TAG:-latest}"
    build:
      context: "./bbb-graphql-middleware"
  graphql-server:
    image: "${IMAGE_REPO:-bigbluebutton}/graphql-server:${IMAGE_GRAPHQL_SERVER_TAG:-latest}"
    build:
      context: "./bbb-graphql-server"
  export-annotations:
    image: "${IMAGE_REPO:-bigbluebutton}/export-annotations:${IMAGE_EXPORT_ANNOTATIONS_TAG:-latest}"
    build:
      context: "./bbb-export-annotations"
  etherpad:
    image: "${IMAGE_REPO:-bigbluebutton}/etherpad:${IMAGE_ETHERPAD_TAG:-latest}"
    build:
      context: "./docker/etherpad"