services:
  web:
    image: "${IMAGE_REPO:-bigbluebutton}/bbb-web:${IMAGE_WEB_TAG:-latest}"
    build:
      tags:
        - "${IMAGE_REPO:-bigbluebutton}/bbb-web:local"
  akka-bbb-apps:
    image: "${IMAGE_REPO:-bigbluebutton}/akka-bbb-apps:${IMAGE_AKKA_BBB_APPS_TAG:-latest}"
    build:
      tags:
        - "${IMAGE_REPO:-bigbluebutton}/akka-bbb-apps:local"
  html5-client:
    image: "${IMAGE_REPO:-bigbluebutton}/html5-client:${IMAGE_HTML5_CLIENT_TAG:-latest}"
    build:
      tags:
        - "${IMAGE_REPO:-bigbluebutton}/html5-client:local"
  learning-dashboard:
    image: "${IMAGE_REPO:-bigbluebutton}/learning-dashboard:${IMAGE_LEARNING_DASHBOARD_TAG:-latest}"
    build:
      tags:
        - "${IMAGE_REPO:-bigbluebutton}/learning-dashboard:local"
  graphql-actions:
    image: "${IMAGE_REPO:-bigbluebutton}/graphql-actions:${IMAGE_GRAPHQL_ACTIONS_TAG:-latest}"
    build:
      tags:
        - "${IMAGE_REPO:-bigbluebutton}/graphql-actions:local"
  graphql-middleware:
    image: "${IMAGE_REPO:-bigbluebutton}/graphql-middleware:${IMAGE_GRAPHQL_MIDDLEWARE_TAG:-latest}"
    build:
      tags:
        - "${IMAGE_REPO:-bigbluebutton}/graphql-middleware:local"
  graphql-server:
    image: "${IMAGE_REPO:-bigbluebutton}/graphql-server:${IMAGE_GRAPHQL_SERVER_TAG:-latest}"
    build:
      tags:
        - "${IMAGE_REPO:-bigbluebutton}/graphql-server:local"
  export-annotations:
    image: "${IMAGE_REPO:-bigbluebutton}/export-annotations:${IMAGE_EXPORT_ANNOTATIONS_TAG:-latest}"
    build:
      tags:
        - "${IMAGE_REPO:-bigbluebutton}/export-annotations:local"
  etherpad:
    image: "${IMAGE_REPO:-bigbluebutton}/etherpad:${IMAGE_ETHERPAD_TAG:-latest}"
    build:
      tags:
        - "${IMAGE_REPO:-bigbluebutton}/etherpad:local"
  record-and-playback:
    container_name: recording-workers
    image: "${IMAGE_REPO:-bigbluebutton}/record-and-playback:${IMAGE_RECORD_AND_PLAYBACK_TAG:-latest}"
    command: "rasque_workers"
    build:
      args:
        TAG_BBB_PRESENTATION_VIDEO: "${TAG_BBB_PRESENTATION_VIDEO:-5.0.0}"
      tags:
        - "${IMAGE_REPO:-bigbluebutton}/record-and-playback:local"
  recording-starter:
    image: "${IMAGE_REPO:-bigbluebutton}/record-and-playback:${IMAGE_RECORD_AND_PLAYBACK_TAG:-latest}"
    command: "rap_starter"
  recording-caption-inbox:
    image: "${IMAGE_REPO:-bigbluebutton}/record-and-playback:${IMAGE_RECORD_AND_PLAYBACK_TAG:-latest}"
    command: "rap_caption_inbox"
  redis:
    image: "redis:8-alpine"
  bbb-nginx:
    image: "${IMAGE_REPO:-bigbluebutton}/bbb-nginx:${IMAGE_BBB_NGINX_TAG:-latest}"
    build:
      tags:
        - "${IMAGE_REPO:-bigbluebutton}/bbb-nginx:local"
