---
services:
  web:
    image: "${IMAGE_REPO:-bigbluebutton}/bbb-web:${IMAGE_WEB_TAG:-latest}"
    build:
      tags:
        - "${IMAGE_REPO:-bigbluebutton}/bbb-web:local"
    restart: unless-stopped
    depends_on:
      - redis
      - etherpad
      - pads
      - collabora
    healthcheck:
      test: curl -s -o /dev/null --spider http://10.7.7.2:8090/bigbluebutton/api || exit 1
      start_period: 2m
    volumes:
      - ./data/bigbluebutton:/var/bigbluebutton
      - ./data/freeswitch-meetings:/var/freeswitch/meetings
    networks:
      bbb-net:

  apps-akka:
    image: "${IMAGE_REPO:-bigbluebutton}/bbb-apps-akka:${IMAGE_APPS_AKKA_TAG:-latest}"
    build:
      tags:
        - "${IMAGE_REPO:-bigbluebutton}/bbb-apps-akka:local"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
    volumes:
      - ./data/freeswitch-meetings:/var/freeswitch/meetings
      - ./conf/bbb-html5.yml:/etc/bigbluebutton/bbb-html5.yml:ro
    networks:
      bbb-net:

  html5-client:
    image: "${IMAGE_REPO:-bigbluebutton}/bbb-html5-client:${IMAGE_HTML5_CLIENT_TAG:-latest}"
    build:
      tags:
        - "${IMAGE_REPO:-bigbluebutton}/bbb-html5-client:local"
    networks:
      bbb-net:

  learning-dashboard:
    image: "${IMAGE_REPO:-bigbluebutton}/bbb-learning-dashboard:${IMAGE_LEARNING_DASHBOARD_TAG:-latest}"
    build:
      tags:
        - "${IMAGE_REPO:-bigbluebutton}/bbb-learning-dashboard:local"
    networks:
      bbb-net:

  graphql-actions:
    image: "${IMAGE_REPO:-bigbluebutton}/bbb-graphql-actions:${IMAGE_GRAPHQL_ACTIONS_TAG:-latest}"
    build:
      tags:
        - "${IMAGE_REPO:-bigbluebutton}/bbb-graphql-actions:local"
    restart: unless-stopped
    depends_on:
      - redis
      - apps-akka
    networks:
      bbb-net:


  graphql-middleware:
    image: "${IMAGE_REPO:-bigbluebutton}/bbb-graphql-middleware:${IMAGE_GRAPHQL_MIDDLEWARE_TAG:-latest}"
    build:
      tags:
        - "${IMAGE_REPO:-bigbluebutton}/bbb-graphql-middleware:local"
    restart: unless-stopped
    depends_on:
      - graphql-server
      - graphql-actions
      - web
      - redis
    networks:
      bbb-net:

  graphql-server:
    image: "${IMAGE_REPO:-bigbluebutton}/bbb-graphql-server:${IMAGE_GRAPHQL_SERVER_TAG:-latest}"
    build:
      tags:
        - "${IMAGE_REPO:-bigbluebutton}/bbb-graphql-server:local"
    restart: unless-stopped
    depends_on:
      - postgres
      - web
      - apps-akka
      - graphql-actions
    networks:
      bbb-net:

  export-annotations:
    image: "${IMAGE_REPO:-bigbluebutton}/bbb-export-annotations:${IMAGE_EXPORT_ANNOTATIONS_TAG:-latest}"
    build:
      tags:
        - "${IMAGE_REPO:-bigbluebutton}/bbb-export-annotations:local"
    restart: unless-stopped
    depends_on:
      - redis
      - web
      - pads
    networks:
      bbb-net:
    volumes:
      - ./data/bigbluebutton:/var/bigbluebutton
    tmpfs:
      - /tmp

  pads:
    image: "${IMAGE_REPO:-bigbluebutton}/bbb-pads:${IMAGE_PADS_TAG:-latest}"
    restart: unless-stopped
    depends_on:
      - redis
      - etherpad
    networks:
      bbb-net:

  etherpad:
    image: "${IMAGE_REPO:-bigbluebutton}/bbb-etherpad:${IMAGE_ETHERPAD_TAG:-latest}"
    build:
      tags:
        - "${IMAGE_REPO:-bigbluebutton}/bbb-etherpad:local"
    restart: unless-stopped
    depends_on:
      - redis
      - collabora
    networks:
      bbb-net:

  record-and-playback:
    container_name: recording-workers
    image: "${IMAGE_REPO:-bigbluebutton}/bbb-record-and-playback:${IMAGE_RECORD_AND_PLAYBACK_TAG:-latest}"
    command: "rasque_workers"
    build:
      args:
        TAG_BBB_PRESENTATION_VIDEO: "${TAG_BBB_PRESENTATION_VIDEO:-5.0.0}"
      tags:
        - "${IMAGE_REPO:-bigbluebutton}/bbb-record-and-playback:local"

  recording-starter:
    image: "${IMAGE_REPO:-bigbluebutton}/bbb-record-and-playback:${IMAGE_RECORD_AND_PLAYBACK_TAG:-latest}"
    command: "rap_starter"

  recording-caption-inbox:
    image: "${IMAGE_REPO:-bigbluebutton}/bbb-record-and-playback:${IMAGE_RECORD_AND_PLAYBACK_TAG:-latest}"
    command: "rap_caption_inbox"

  recording-cleanup:
    image: "${IMAGE_REPO:-bigbluebutton}/bbb-record-and-playback:${IMAGE_RECORD_AND_PLAYBACK_TAG:-latest}"
    command: "cleanup"
    env_file:
      - .env

  webrtc-sfu:
    image: "${IMAGE_REPO:-bigbluebutton}/bbb-webrtc-sfu:${IMAGE_WEBRTC_SFU_TAG:-latest}"
    restart: unless-stopped
    networks:
      bbb-net:

  nginx:
    image: "${IMAGE_REPO:-bigbluebutton}/bbb-nginx:${IMAGE_NGINX_TAG:-latest}"
    build:
      tags:
        - "${IMAGE_REPO:-bigbluebutton}/bbb-nginx:local"
    depends_on:
      - web
      - etherpad
      - html5-client
      - webhooks
      - webrtc-sfu
      - graphql-server
      - graphql-middleware
      - livekit

  webhooks:
    image: "${IMAGE_REPO:-bigbluebutton}/bbb-webhooks:${IMAGE_WEBHOOKS_TAG:-latest}"

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      bbb-net:

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_MULTIPLE_DATABASES: bbb_graphql,hasura_app,greenlight
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./docker/postgres/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    networks:
      bbb-net:

  collabora:
    image: collabora/code:latest
    restart: unless-stopped
    tmpfs:
      - /tmp
    networks:
      bbb-net:
    # disable logging (way to verbose)
    logging:
      driver: none

networks:
  bbb-net:
