exports.TEST_DURATION_TIME = 3600000;
exports.USER_LIST_VLIST_BOTS_TALKING = 1;
exports.USER_LIST_VLIST_BOTS_LISTENING = 100;
exports.CAMERA_SHARE_FAILED_WAIT_TIME = 15000;
exports.LOOP_INTERVAL = 1000;
