// include default config from upstream
include "/bbb-apps-akka/conf/application.conf"

redis {
    host="redis"
}

services {
  bbbWebAPI="https://web/bigbluebutton/api"
  graphqlMiddlewareAPI = "http://graphql-middleware:8378"
}
http {
  interface = "0.0.0.0"
}

postgres {
  properties = {
      serverName = "postgres"
      databaseName = "bbb_graphql"
  }
}