// include default config from upstream
include "/bbb-apps-akka/conf/application.conf"

redis {
    host="redis"
}

services {
  bbbWebAPI="https://web/bigbluebutton/api"
  graphqlMiddlewareAPI = "http://10.7.7.32:8378"
}
http {
  interface = "0.0.0.0"
}

postgres {
  properties = {
      serverName = "postgres"
      portNumber = "5432"
      databaseName = "bbb_graphql"
      user = "postgres"
  }
}