exports.autoJoin = 'userdata-autoJoin=false';
exports.listenOnlyMode = 'userdata-listenOnlyMode=false';
exports.forceListenOnly = 'userdata-forceListenOnly=true';
exports.skipCheck = 'userdata-skipCheck=true';
const docTitle = 'puppeteer';
exports.docTitle = docTitle;
exports.clientTitle = `userdata-clientTitle=${docTitle}`;
exports.askForFeedbackOnLogout = 'userdata-askForFeedbackOnLogout=true';
exports.displayBrandingArea = 'userdata-displayBrandingArea=true';
exports.logo = 'logo=https://bigbluebutton.org/wp-content/themes/bigbluebutton/library/images/bigbluebutton-logo.png';
exports.shortcuts = 'userdata-shortcuts=["openOptions", "toggleUserList", "toggleMute", "joinAudio", "leaveAudio", "togglePublicChat", "hidePrivateChat", "closePrivateChat", "openActions", "openStatus"]';
exports.enableScreensharing = 'userdata-enableScreensharing=false';
exports.enableVideo = 'userdata-enableVideo=false';
exports.autoShareWebcam = 'userdata-autoShareWebcam=true';
exports.multiUserPenOnly = 'userdata-multiUserPenOnly=true';
exports.presenterTools = 'userdata-presenterTools=["pencil", "hand"]';
exports.multiUserTools = 'userdata-multiUserTools=["pencil", "hand"]';
exports.customStyle = 'userdata-customStyle=:root{--loader-bg:#000;}.overlay--1aTlbi{background-color:#000!important;}body{background-color:#000!important;}.presentationTitle--1LT79g{display: none;}.navbar--Z2lHYbG{display:none;}.actionsbar--Z1ant6U{display:none;}';
exports.customStyleUrl = 'userdata-customStyleUrl=https://bbb22.bbbvm.imdt.com.br/styles.css';
exports.autoSwapLayout = 'userdata-autoSwapLayout=true';
exports.hidePresentation = 'userdata-hidePresentation=false';
// exports.outsideToggleSelfVoice...;
// exports.outsideToggleRecording...;
exports.bannerText = 'bannerText=some text';
exports.color = '111111';
exports.bannerColor = `bannerColor=%23${this.color}`;
