exports.autoJoin = 'userdata-autoJoin=false';
exports.listenOnlyMode = 'userdata-listenOnlyMode=false';
exports.forceListenOnly = 'userdata-forceListenOnly=true';
exports.skipCheck = 'userdata-skipCheck=true';
const docTitle = 'puppeteer';
exports.docTitle = docTitle;
exports.clientTitle = `userdata-clientTitle=${docTitle}`;
exports.askForFeedbackOnLogout = 'userdata-askForFeedbackOnLogout=true';
exports.displayBrandingArea = 'userdata-displayBrandingArea=true';
exports.logo = 'logo=https://bigbluebutton.org/wp-content/themes/bigbluebutton/library/images/bigbluebutton-logo.png';
exports.shortcuts = 'userdata-shortcuts=["openOptions", "toggleUserList", "toggleMute", "joinAudio", "leaveAudio", "togglePublicChat", "hidePrivateChat", "closePrivateChat", "openActions", "openStatus"]';
exports.enableScreensharing = 'userdata-enableScreensharing=false';
exports.enableVideo = 'userdata-enableVideo=false';
exports.autoShareWebcam = 'userdata-autoShareWebcam=true';
