exports.audioModal = 'div[aria-label="Join audio modal"]';
exports.audioOverlay = 'div[class^="ReactModal__Overlay"]';
exports.whiteboard = 'svg[data-test="whiteboard"]';
exports.echoTestYesButton = 'button[aria-label="Echo is audible"]';
exports.echoTestNoButton = 'button[aria-label="Echo is inaudible"]';
exports.audioNotification = 'div[class^="toastContainer--"]';
exports.options = 'button[aria-label="Options"]';
exports.logout = 'li[data-test="logout"]';
exports.meetingEndedModal = 'div[data-test="meetingEndedModal"]';
exports.rating = 'div[data-test="rating"]';
exports.brandingAreaLogo = 'div[class^="branding--"]';
exports.verticalListOptions = 'div[aria-expanded="true"] > div[class^="scrollable--"] > ul[class^="verticalList"]';
exports.screenShareButton = 'button[aria-label="Share your screen"]';
exports.shareWebcamButton = 'button[aria-label="Share webcam"]';
exports.webcamSettingsModal = 'div[aria-label="Webcam settings"]';
exports.startWebcamSharingConfirm = 'button[aria-label="Start sharing"]';
