exports.audioModal = 'div[aria-label="Join audio modal"]';
exports.audioOverlay = 'div[class^="ReactModal__Overlay"]';
exports.whiteboard = 'svg[data-test="whiteboard"]';
exports.echoTestYesButton = 'button[aria-label="Echo is audible"]';
exports.echoTestNoButton = 'button[aria-label="Echo is inaudible"]';
exports.toastContainer = 'div[class^="toastContainer--"]';
exports.muteBtn = 'button[aria-label="Mute"]';
exports.options = 'button[aria-label="Options"]';
exports.logout = 'li[data-test="logout"]';
exports.meetingEndedModal = 'div[data-test="meetingEndedModal"]';
exports.rating = 'div[data-test="rating"]';
exports.brandingAreaLogo = 'div[class^="branding--"]';
exports.verticalListOptions = 'div[aria-expanded="true"] > div[class^="scrollable--"] > ul[class^="verticalList"]';
exports.screenShareButton = 'button[aria-label="Share your screen"]';
exports.shareWebcamButton = 'button[data-test="joinVideo"]';
exports.stopWebcamButton = 'button[data-test="leaveVideo"]';
exports.webcamSettingsModal = 'div[aria-label="Webcam settings"]';
exports.startWebcamSharingConfirm = 'button[aria-label="Start sharing"]';
exports.multiUsersWhiteboard = 'button[aria-label="Turn multi-user whiteboard on"]';
exports.tools = 'button[aria-label="Tools"]';
exports.actions = 'button[aria-label="Actions"]';
exports.hidePresentation = 'button[data-test="hidePresentationButton"]';
exports.restorePresentation = 'button[data-test="restorePresentationButton"]';
exports.container = 'div[id="container"]';
exports.defaultContent = 'div[class^="defaultContent--"]';
exports.notificationBar = 'div[class^="notificationsBar--"]';
exports.chat = 'section[aria-label="Chat"]';
exports.recordingIndicator = 'div[class^="recordingIndicator--"]';
exports.startSharingWebcamButton = 'button[data-test="startSharingWebcam"]';
exports.webcamVideoPreview = 'video[data-test="videoPreview"]';
exports.webcamMirroredVideoPreview = 'video[data-test="mirroredVideoPreview"]';
exports.webcamVideoContainer = 'video[data-test="videoContainer"]';
exports.webcamMirroredVideoContainer = 'video[data-test="mirroredVideoContainer"]';
exports.userslistContainer = 'div[aria-label="User list"]';
exports.userListContent = 'div[data-test="userListContent"]';
exports.confirmBtn = 'button[aria-label="Confirm "]';
