exports.audioModal = 'div[aria-label="Join audio modal"]';
exports.audioOverlay = 'div[class^="ReactModal__Overlay"]';
exports.whiteboard = 'svg[data-test="whiteboard"]';
exports.echoTestYesButton = 'button[aria-label="Echo is audible"]';
exports.echoTestNoButton = 'button[aria-label="Echo is inaudible"]';
exports.audioNotification = 'div[class^="toastContainer--"]';
exports.options = 'button[aria-label="Options"]';
exports.logout = 'li[data-test="logout"]';
exports.meetingEndedModal = 'div[data-test="meetingEndedModal"]';
exports.rating = 'div[data-test="rating"]';
