table:
  name: v_user_clientSettings
  schema: public
configuration:
  column_config: {}
  custom_column_names: {}
  custom_name: user_clientSettings
  custom_root_fields: {}
select_permissions:
  - role: bbb_client
    permission:
      columns:
        - userClientSettingsJson
        - userId
      filter:
        _and:
          - meetingId:
              _eq: X-Hasura-MeetingId
          - userId:
              _eq: X-Hasura-UserId
