table:
  name: v_user_lockSettings
  schema: public
configuration:
  column_config: {}
  custom_column_names: {}
  custom_name: user_lockSettings
  custom_root_fields: {}
select_permissions:
  - role: bbb_client
    permission:
      columns:
        - disablePublicChat
      filter:
        meetingId:
          _eq: X-Hasura-MeetingId
      query_root_fields: []
      subscription_root_fields: []
    comment: ""
