package org.bigbluebutton.core.api

object Constants {
  val NAME                            = "name"
  val HEADER                          = "header"
  val PAYLOAD                         = "payload"
  val MEETING_ID                      = "meeting_id"
  val TIMESTAMP                       = "timestamp"
  val USER_ID                         = "user_id"
  val RECORDED                        = "recorded"
  val MEETING_NAME                    = "meeting_name"
  val VOICE_CONF                      = "voice_conf"
  val DURATION                        = "duration"
  val AUTH_TOKEN                      = "auth_token"
  val ROLE                            = "role"
  val EXT_USER_ID                     = "external_user_id"
  val REQUESTER_ID                    = "requester_id"
  val REPLY_TO                        = "reply_to"
  val LOWERED_BY                      = "lowered_by"
  val STREAM                          = "stream"
  val LOCKED                          = "locked"
  val SETTINGS                        = "settings"
  val LOCK                            = "lock"
  val EXCEPT_USERS                    = "except_users"
  val STATUS                          = "status"
  val VALUE                           = "value"
  val NEW_PRESENTER_ID                = "new_presenter_id"
  val NEW_PRESENTER_NAME              = "new_presenter_name"
  val ASSIGNED_BY                     = "assigned_by"
  val RECORDING                       = "recording" 
  val LAYOUT_ID                       = "layout_id"
  val POLL                            = "poll"
  val POLL_ID                         = "poll_id"
    
}