exports.pollingContainer = 'div[data-test="pollingContainer"]';
exports.pollQuestionArea = 'textarea[data-test="pollQuestionArea"]';
exports.pollQuestion = 'Are we good ?';
exports.responseTypes = 'div[data-test="responseTypesLabel"]';
exports.responseChoices = 'div[data-test="responseChoices"]';
exports.addItem = 'button[data-test="addItem"]';
exports.pollOptionItem = 'input[data-test="pollOptionItem"]';
exports.uncertain = 'Uncertain';
exports.deletePollOption = 'button[data-test="deletePollOption"]';
exports.pollAnswerOptionBtn = 'button[data-test="pollAnswerOption"]';
exports.pollAnswerOptionInput = 'input[data-test="pollAnswerOption"]';
exports.pollSubmitAnswer = 'button[data-test="submitAnswer"]';
exports.startPoll = 'button[data-test="startPoll"]';
exports.receivedAnswer = 'td[data-test="receivedAnswer"]';
exports.publishLabel = 'button[data-test="publishLabel"]';
