#!/bin/sh

#
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/
#
# Copyright (c) 2010 BigBlueButton Inc. and by respective authors (see below).
#
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 2.1 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
# 

test -x /var/bigbluebutton || exit 0

#
# Disable this cron job for now (the administrator can manually enable it).
#
# We disable it for now to ensure if rap-worker.rb didn't archive a recording
# we can try and archive it again without having the source files deleted.
#
exit 0

#
# Delete presentations older than a day
#
find /var/bigbluebutton -maxdepth 1 -type d -name "*-*" -mtime +11 -exec rm -r '{}' \;

#
# Delete webcam streams in red5 older than one day
#
find /usr/share/red5/webapps/video/streams -name "*.flv" -mtime +1 -exec rm '{}' \;

#
# Delete desktop sharing streams in red5 older than one day
#
find /var/bigbluebutton/deskshare -name "*.flv" -mtime +1 -exec rm '{}' \;

#
# Delete FreeSWITCH wav recordings older than one day
#
find /var/freeswitch/meetings -name "*.wav" -mtime +1 -exec rm '{}' \;

