#!/bin/bash

# for psql
export PGHOST=postgres
export PGUSER="${BBB_POSTRES_USER}"
export PGPASSWORD="${BBB_POSTGRES_PASSWORD}"


# for hasura
export HASURA_GRAPHQL_DATABASE_URL=postgres://${BBB_POSTRES_USER}:${BBB_POSTGRES_PASSWORD}@postgres:5432/hasura_app
export HASURA_GRAPHQL_METADATA_DATABASE_URL=postgres://${BBB_POSTRES_USER}:${BBB_POSTGRES_PASSWORD}@postgres:5432/hasura_app
export HASURA_GRAPHQL_LOG_LEVEL=warn
export HASURA_GRAPHQL_ENABLE_CONSOLE=false
export HASURA_GRAPHQL_LIVE_QUERIES_MULTIPLEXED_REFETCH_INTERVAL=250
export HASURA_GRAPHQL_LIVE_QUERIES_MULTIPLEXED_BATCH_SIZE=1000
export HASURA_GRAPHQL_STREAMING_QUERIES_MULTIPLEXED_REFETCH_INTERVAL=100
export HASURA_GRAPHQL_STREAMING_QUERIES_MULTIPLEXED_BATCH_SIZE=1000
export HASURA_GRAPHQL_SERVER_PORT=8085
export HASURA_GRAPHQL_ENABLE_TELEMETRY=false
export HASURA_GRAPHQL_WEBSOCKET_KEEPALIVE=10
export HASURA_GRAPHQL_AUTH_HOOK=http://apps-akka:8901/userInfo
export HASURA_BBB_GRAPHQL_ACTIONS_ADAPTER_URL=http://bbb-graphql-actions:8093


export HASURA_GRAPHQL_BBB_DATABASE_URL=postgres://${BBB_POSTRES_USER}:${BBB_POSTGRES_PASSWORD}@postgres:5432/bbb_graphql

exec $@