exports.firstUser = '[data-test="userListItemCurrent"]';
exports.userListItem = '[data-test="userListItem"]';
exports.anyUser = '[data-test^="userListItem"]';
exports.setStatus = '[data-test="setstatus"]';
exports.away = '[data-test="away"]';
exports.applaud = '[data-test="applause"]';
exports.applauseIcon = 'div[data-test="userAvatar"] > div > i[class="icon-bbb-applause"]';
exports.awayIcon = 'div[data-test="userAvatar"] > div > i[class="icon-bbb-time"]';
exports.clearStatus = '[data-test="clearStatus"]';
exports.statusIcon = '[data-test="userAvatar"]';
exports.setPresenter = 'li[data-test="setPresenter"]';
exports.connectionStatusModal = 'div[aria-label="Connection status modal"]';
exports.dataSavingWebcams = 'input[data-test="dataSavingWebcams"]';
exports.dataSavingScreenshare = 'input[data-test="dataSavingScreenshare"]';
exports.closeConnectionStatusModal = 'button[aria-label="Close Connection status modal"]';
exports.webcamsIsDisabledInDataSaving = 'button[aria-label="Webcam sharing is disabled in Data Saving"]';
exports.screenshareLocked = 'button[aria-label="Screenshare locked"]';
exports.connectionStatusItemEmpty = 'div[data-test="connectionStatusItemEmpty"]';
exports.connectionStatusItemUser = 'div[data-test="connectionStatusItemUser"]';
exports.mobileUser = 'span[data-test="mobileUser"]';
exports.userList = '[aria-label="Users and messages toggle"]';
