const reactionsButton: string = 'button[data-test="reactionsButton"]';
const baseBbbIcon: string = 'i.icon-bbb-';
const pollOptionItem: string = 'input[data-test="pollOptionItem"]';
const pollAnswerOptionDesc: string = 'div[data-test="optionsAnswers"]';
const pollAnswersOption: string = 'div[data-test="optionsAnswers"]';
const userAvatar: string = 'div[data-test-avatar="userAvatar"]';
const networkDataContainer: string = 'div[data-test="networkDataContainer"]';

export const elements = {
  // Common
  actions: 'button[data-test="actionsButton"]',
  actionsItem: 'div[id="actions-dropdown-menu"] ul li',
  presentationNames: 'div[data-test="presentationName"]',
  presentationThumbnails: 'button[data-test="presentationThumbnail"]',
  sharePresentationButton: 'button[data-test="sharePresentationButton"]',
  mediaAreaButton: 'button[data-test="mediaAreaButton"]',
  mediaAreaItem: 'div[id="media-area-dropdown-menu"] ul li',
  optionsButton: 'button[data-test="optionsButton"]',
  modalConfirmButton: 'button[data-test="modalConfirmButton"]',
  screenshareConnecting: 'div[data-test="screenshareConnecting"]',
  screenShareVideo: 'video[id="screenshareVideo"]',
  simpleModal: 'div[id="simpleModal"]',
  sessionDetailsModal: 'div[data-test="sessionDetailsModal"]',
  modalDismissButton: 'button[data-test="modalDismissButton"]',
  closeModal: 'button[data-test="closeModal"]',
  isSharingScreen: 'div[data-test="isSharingScreen"]',
  pdfFileName: '100PagesFile.pdf',
  reactionsButton,
  reactionsButtonLabel: `${reactionsButton} span:nth-child(2)`,
  singleReactionButton: 'li[data-test="reaction"]',
  emojiRain: 'div[data-test="emojiRain"] svg',
  raiseHandBtn: 'button[data-test="raiseHandBtn"]',
  lowerHandBtn: 'button[data-test="lowerHandBtn"]',
  raiseHandRejection: 'button[data-test="raiseHandRejection"]',
  raiseHandWrapper: 'div[data-test="raiseHandWrapper"]',
  meetingEndedModal: 'div[data-test="meetingEndedModal"]',
  redirectButton: 'button[data-test="redirectButton"]',
  leaveMeetingDropdown: 'button[data-test="leaveMeetingDropdown"]',
  directLogoutButton: 'li[data-test="directLogoutButton"]',
  returnToMainRoomButton: 'li[data-test="returnToMainRoomButton"]',
  optionsLogoutButton: 'li[data-test="optionsLogoutButton"]',
  endMeetingButton: 'li[data-test="endMeetingButton"]',
  confirmEndMeetingButton: 'button[data-test="confirmEndMeeting"]',
  rating: 'div[data-test="rating"]',
  sendFeedbackButton: 'button[data-test="sendFeedbackButton"]',
  feedbackCommentInput: 'textarea#feedbackComment',
  errorScreenMessage: 'h1[data-test="errorScreenMessage"]',
  errorMessageLabel: 'span[id="error-message"]',
  shareCameraAsContent: 'div[data-test="cameraAsContent"]',
  closePopup: 'button[data-test="closePopup"]',
  restoreWelcomeMessages: 'li[data-test="restoreWelcomeMessages"]',
  navigationSidebarContainer: 'div[data-test="navigationSidebarContainer"]',
  appsGallerySidebarButton: 'div[data-test="appsGallerySidebarButton"]',

  // Accesskey
  userListButton: 'button[accesskey="U"]',

  // Audio
  joinAudio: 'button[data-test="joinAudio"]',
  audioModal: 'div[data-test="audioModal"]',
  audioSettingsModal: 'div[data-test="audioSettingsModal"]',
  listenOnlyButton: 'button[data-test="listenOnlyBtn"]',
  testSpeakerButton: 'button[data-test="testSpeakerButton"]',
  stopHearingButton: 'button[data-test="stopHearingButton"]',
  joinEchoTestButton: 'button[data-test="joinEchoTestButton"]',
  establishingAudioLabel: 'span[data-test="establishingAudioLabel"]',
  selectMicrophoneButton: 'label[for="inputDeviceSelector"] select',
  leaveListenOnly: 'button[data-test="leaveListenOnly"]',
  leaveAudio: 'li[data-test="leaveAudio"]',
  audioDropdownMenu: 'button[data-test="audioDropdownMenu"]',
  defaultInputAudioDevice: 'li[data-test="audioinput-1"]',
  secondInputAudioDevice: 'li[data-test="audioinput-2"]',
  microphoneButton: 'button[data-test="microphoneBtn"]',
  connectingToEchoTest: 'span[data-test="connectingToEchoTest"]',
  hasVolumeEchoTest: 'span[data-test="hasVolume"]',
  hasNoVolumeEchoTest: 'span[data-test="hasNoVolume"]',
  isTalking: 'button[data-test="isTalking"]',
  wasTalking: 'button[data-test="wasTalking"]',
  talkingIndicator: 'div[data-test="talkingIndicator"]',
  unmuteMicButton: 'button[data-test="unmuteMicButton"]',
  muteMicButton: 'button[data-test="muteMicButton"]',
  speechRecognition: 'select[id="speechSelect"]',
  speechRecognitionUnsupported: 'div[data-test="speechRecognitionUnsupported"]',

  // Breakout
  createBreakoutRoomsButton: 'button[data-test="createBreakoutRoomsButton"]',
  updateBreakoutRoomsButton: 'button[data-test="updateBreakoutRoomsButton"]',
  breakoutRoomSidebarButton: 'div[data-test="breakoutroomSidebarButton"]',
  randomlyAssign: 'button[data-test="randomlyAssign"]',
  resetAssignments: 'button[data-test="resetAssignments"]',
  breakoutRoomsItem: 'div[data-test="breakoutRoomsItem"]',
  alreadyConnected: 'button[data-test="alreadyConnected"]',
  askJoinRoom1: 'button[data-test="askToJoinRoom1"]',
  askJoinRoom2: 'button[data-test="askToJoinRoom2"]',
  roomOptions2: 'button[data-test="roomOptions2"]',
  joinRoom1: 'button[data-test="joinRoom1"]',
  joinFirstRoom: 'button[data-test^="joinRoom"]',
  allowChoiceRoom: 'input[id="opt-freeJoin"]',
  labelGeneratingURL: 'span[data-test="labelGeneratingURL"]',
  endBreakoutRoomsButton: 'button[data-test="endBreakoutRoomsButton"]',
  durationTime: 'input[data-test="durationTime"]',
  minimumDurationWarnBreakout: 'span[data-test="minimumDurationWarnBreakout"]',
  selectNumberOfRooms: 'select[id="numberOfRooms"]',
  increaseRooms: 'button[data-test="increaseRooms"]',
  decreaseRooms: 'button[data-test="decreaseRooms"]',
  roomGrid: 'div[data-test="roomGrid"] >> input',
  breakoutBox0: 'div[id="breakoutBox-0"]',
  breakoutBox1: 'div[id="breakoutBox-1"]',
  breakoutBox2: 'div[id="breakoutBox-2"]',
  breakoutOptionsMenu: 'button[data-test="breakoutOptionsMenu"]',
  openUpdateBreakoutUsersModal: 'li[data-test="openUpdateBreakoutUsersModal"]',
  attendeeNotAssigned: 'div[id="breakoutBox-0"] [data-test="draggableUser"]:first-child',
  moveUser: 'div[id="breakoutBox-1"] [data-test="draggableUser"]:first-child',
  openBreakoutTimeManager: 'li[data-test="openBreakoutTimeManager"]',
  inputSetTimeSelector: 'input[id="inputSetTimeSelector"]',
  sendButtonDurationTime: 'button[data-test="sendButtonDurationTime"]',
  breakoutRemainingTime: 'div[data-test="breakoutRemainingTime"]',
  breakoutRoomTimerHoursInput: 'input[data-test="breakoutRoomTimerHoursInput"]',
  breakoutRoomTimerMinutesInput: 'input[data-test="breakoutRoomTimerMinutesInput"]',
  increaseBreakoutTimeButton: 'button[data-test="increaseBreakoutTimeButton"]',
  decreaseBreakoutTimeButton: 'button[data-test="decreaseBreakoutTimeButton"]',
  roomName1: 'span[data-test="Room 1"]',
  roomName2: 'span[data-test="Room 2"]',
  roomNameInput1: 'input[data-test="roomName-1"]',
  roomNameInput2: 'input[data-test="roomName-2"]',
  roomName1Test: 'span[data-test="TestRoom 1"]',
  breakoutRoomItemOnManage: 'span[data-test^="Room"]',
  userNameBreakoutRoom: 'span[data-test="userNameBreakoutRoom-Room 1"]',
  userNameBreakoutRoom2: 'span[data-test="userNameBreakoutRoom-Room 2"]',
  userNameBreakoutRoom7: 'span[data-test="userNameBreakoutRoom-Room 7"]',
  endAllBreakouts: 'li[data-test="endAllBreakouts"]',
  finishBreakoutButton: 'button[data-test="finishBreakoutButton"]',
  breakoutRoomList: 'div[data-test="breakoutRoomList"]',
  warningNoUserAssigned: 'span[data-test="warningNoUserAssigned"]',
  timeRemaining: 'span[data-test="timeRemaining"]',
  captureBreakoutSharedNotes: 'input[id="opt-captureNotes"]',
  captureBreakoutWhiteboard: 'input[id="opt-captureSlides"]',
  selectBreakoutRoomBtn: 'select[data-test="selectBreakoutRoomBtn"]',
  roomOption: 'option[data-test="roomOption"]',
  changeSlideBreakoutRoom1: 'div[data-test="changeSlideBreakoutRoom1"]',
  slide1BreakoutRoom: 'select[data-test="changeSlideBreakoutRoom"]',
  currentSlideBreakoutOption: 'option[data-test="currentSlideBreakoutOption"]',
  moreOptionsToggle: 'button[data-test="moreOptionsToggle"]',
  breakoutJoinConfirmationDialog: 'div[data-test="breakoutJoinConfirmationDialog"]',
  breakoutMegaphoneButton: 'button[data-test="megaphoneButton"]',
  breakoutMessageInput: 'input[data-test="messageInput"]',
  callModeratorButton: 'button[data-test="callModeratorButton"]',
  returnToMainSessionButton: 'button[data-test="returnToMainSessionButton"]',

  // Chat
  chatBox: 'textarea[id="message-input"]',
  chatMessageItem: 'div[data-test="chatMessageItem"]',
  partnerDisconnectedMessage: 'span[data-test="partnerDisconnected"]',
  chatButton: 'button[data-test*="ChatButton"]',
  messagesSidebarButton: 'div[data-test="messagesSidebarButton"]',
  sendButton: 'button[data-test="sendMessageButton"]',
  chatPollMessageText: 'div[data-test="chatPollMessageText"]',
  chatMessages: 'div[data-test="chatMessages"]',
  chatOptions: 'button[data-test="chatOptionsMenu"]',
  chatClear: 'li[data-test="chatClear"]',
  chatSave: 'li[data-test="chatSave"]',
  chatCopy: 'li[data-test="chatCopy"]',
  chatTitle: 'header[data-test="chatTitle"]',
  startPrivateChat: 'div[data-test="startPrivateChat"]',
  publicChatButton: 'button[data-test="publicChatButton"]',
  privateChatButton: 'button[data-test="privateChatButton"]',
  privateChatItem: 'button[data-test="privateChatItem"]',
  publicUnreadIndicator: 'span[data-test="publicUnreadIndicator"]',
  privateUnreadIndicator: 'span[data-test="privateUnreadIndicator"]',
  privateChats: 'div[data-test="private-user-list-header"]',
  privateChat: 'div[data-test="messageContent"] p>>nth=1',
  hidePublicChat: 'button[data-test="hidePublicChat"]',
  hidePrivateChat: 'button[data-test="hidePrivateChat"]',
  hideMessagesButton: 'button[data-test="hideMessagesButton"]',
  privateChatBackButton: 'div[data-test="privateChatBackButton"]',
  typingIndicator: 'span[data-test="typingIndicator"]',
  errorTypingIndicator: 'div[data-test="errorTypingIndicator"]',
  chatUserMessageText: 'div[data-test="messageContent"] p',
  chatNotificationMessageText: 'div[data-test="chatMessageNotificationContent"] p',
  secondChatUserMessageText: 'p[data-test="chatUserMessageText"]>>nth=1',
  chatWelcomeMessageText: 'div[data-test="welcomeMessage"]',
  waitingUsersLobbyMessage: 'div[data-test="lobbyMessage"] >> textarea',
  sendLobbyMessage: 'div[data-test="lobbyMessage"] >> button',
  lobbyMessage: 'div[data-test="lobbyMessage"] >> p',
  positionInWaitingQueue: 'div[id="positionInWaitingQueue"]',
  allowEveryone: 'button[data-test="allowEveryone"]',
  denyEveryone: 'button[data-test="denyEveryone"]',
  guestMessage: 'p[data-test="guestMessage"]',
  privateMessageGuest: 'button[data-test="privateMessageGuest"]',
  acceptGuest: 'button[data-test="acceptGuest"]',
  denyGuest: 'button[data-test="denyGuest"]',
  inputPrivateLobbyMessage: 'div[data-test="privateLobbyMessage"] >> textarea',
  sendPrivateLobbyMessage: 'div[data-test="privateLobbyMessage"] >> button',
  rememberCheckboxId: 'input[id="rememberCheckboxId"]',
  welcomeMessage: 'h1[id="welcome-message"]',
  chatMessageEditedLabel: 'span[data-test="chatMessageEditedLabel"]',
  chatEditingWarningContainer: 'div[data-test="chatEditingWarningContainer"]',
  cancelEditingButton: 'button[data-test="cancelEditingButton"]',
  confirmDeleteChatMessageButton: 'button[data-test="confirmDeleteChatMessageButton"]',
  chatReplyIntentionContainerContent: 'div[data-test="chatReplyIntentionContainer"] p',
  closeChatReplyIntentionButton: 'button[data-test="closeChatReplyIntentionButton"]',
  chatMessageReplied: 'div[data-test="chatMessageReplied"]',
  messageReactionItem: 'button[data-test="messageReactionItem"]',

  // Message toolbar
  messageToolbar: 'div[data-test="chatMessageToolbar"]',
  replyMessageButton: 'button[data-test="replyMessageButton"]',
  reactMessageButton: 'button[data-test="reactMessageButton"]',
  editMessageButton: 'button[data-test="editMessageButton"]',
  deleteMessageButton: 'button[data-test="deleteMessageButton"]',

  // Emoji picker
  emojiPickerButton: 'button[data-test="emojiPickerButton"]',
  thumbsUpEmoji: '👍',
  grinningFaceEmoji: '😀',

  // Auto Convert Emoji
  autoConvertEmojiMessage: ':)',
  convertedEmojiMessage: '😊',

  // Messages
  message: 'Hello World!',
  testMessage: 'Just a test',
  message1: 'Hello User2',
  message2: 'Hello User1',
  publicMessage1: 'This is a Public Message from User1',
  publicMessage2: 'This is a Public Message from User2',
  uniqueCharacterMessage: 'A',

  // CustomParameters
  audioOptionsButtons: 'span[data-test="audioModalOptions"] > button',
  userListContainer: 'div[data-test="userListContainer"]',
  userListContent: 'div[data-test="userListContent"]',
  brandingAreaLogo: 'div[data-test="brandingArea"]',
  toolbarToolsList: 'div[data-test="toolbarToolsList"]',
  notificationBannerBar: 'div[data-test="notificationBannerBar"]',
  reconnectingBar: '//div[@data-test="notificationBannerBar" and contains(text(), "Reconnection in progress")]',
  zoomInBtn: 'button[data-test="zoomInBtn"]',
  recordingIndicator: 'div[data-test="recordingIndicator"]',
  webcamMirroredVideoContainer: 'video[data-test="mirroredVideoContainer"]',
  currentUserLocalStreamVideo: 'video[data-local-stream="true"]',
  usersList: 'div[data-test="userList"]',
  selectCameraQualityId: 'select[id="setQuality"]',
  virtualBackgrounds: 'div[data-test="virtualBackground"]',

  // Timer
  timerContainer: 'div[data-test="timerContainer"]',
  stopwatchContainer: 'div[data-test="stopwatchContainer"]',
  timerStopwatchFeature: 'div[data-test="timerSidebarButton"]',
  stopwatchCurrent: 'span[data-test="stopwatchCurrent"]',
  timerCurrent: 'div[data-test="timerCurrent"]',
  startStopTimer: 'button[data-test="startStopTimer"]',
  resetTimerStopwatch: 'button[data-test="resetTimerStopWatch"]',
  timerButton: 'button[data-test="timerButton"]',
  timerIndicator: 'div[data-test="timeIndicator"]',
  stopwatch: 'button[data-test="stopwatchButton"]',
  hoursInput: 'input[data-test="hoursInput"]',
  minutesInput: 'input[data-test="minutesInput"]',
  secondsInput: 'input[data-test="secondsInput"]',
  timerHeader: 'header[data-test="timerHeader"]',

  // Notes
  sharedNotesSidebarButton: 'div[data-test="sharedNotesSidebarButton"]',
  hideNotesLabel: 'button[data-test="hideNotesLabel"]',
  etherpadFrame: 'iframe[title="pad"]',
  etherpadOuter: 'iframe[title="Ether"]',
  etherpadInner: 'iframe[title="pad"]',
  etherpadEditable: 'body[id="innerdocbody"]',
  sendNotesToWhiteboard: 'li[data-test="moveNotesToWhiteboard"]',
  presentationUploadProgressToast: 'div[data-test="presentationUploadProgressToast"]',
  sharedNotesViewingMode: 'iframe[title="shared notes viewing mode"]',
  currentSlideText: 'span[id="currentSlideText"]',
  notesOptions: 'button[data-test="notesOptionsMenu"]',
  showMoreSharedNotesButton: 'span[class="show-more-icon-btn"]',
  exportSharedNotesButton: 'li[data-key="import_export"] button',
  exportPlainButton: 'a[id="exportplaina"] span',
  pinNotes: 'li[data-test="pinNotes"]',
  unpinNotes: 'button[data-test="unpinNotes"]',
  exportetherpad: 'span[id="exportetherpad"]',
  exporthtml: 'span[id="exporthtml"]',

  // Notifications
  smallToastMsg: 'div[data-test="toastSmallMsg"]',
  closeToastBtn: 'i[data-test="closeToastBtn"]',
  notificationsTab: 'span[id="notificationTab"]',
  chatPopupAlertsBtn: 'input[data-test="chatPopupAlertsBtn"]',
  hasUnreadMessages: 'div[data-test="unreadMessages"]',
  userJoinPushAlerts: 'input[data-test="userJoinPopupAlerts"]',
  toastContainer: 'div[data-test="toastContainer"]',
  presentationStatusInfo: 'span[data-test="presentationStatusInfo"]',
  processingPresentationItem: 'span[data-test="processingPresentationItem"]',
  uploadDoneIcon: 'i[data-test="uploadDoneIcon"]',
  noButton: 'button[aria-label="No"]',
  yesButton: 'button[aria-label="Yes"]',
  cancelRecordingButton: 'button[data-test="cancelRecordingButton"]',
  confirmRecordingButton: 'button[data-test="confirmRecordingButton"]',

  // Toasts
  savedSettingsToast: 'Settings have been saved',
  publicChatToast: 'New Public Chat message',
  privateChatToast: 'New Private Chat message',
  joinAudioToast: 'You have joined the audio conference',
  leftAudioToast: 'You have left the audio conference',
  pollPublishedToast: 'Poll results were published',
  startScreenshareToast: 'Screenshare has started',
  endScreenshareToast: 'Screenshare has ended',
  attendeeJoinedToast: 'Attendee joined the session',
  raisingHandToast: 'You have raised your hand',
  loweringHandToast: 'Your hand has been lowered',
  noActiveMicrophoneToast: 'No active microphone. Share your microphone to add audio to this recording.',
  whiteboardAvailableToast: 'The whiteboard is now available',
  whiteboardDisabledToast: 'The whiteboard access has been removed',
  inviteSentRoom1: 'Attendee was invited to Room 1',
  inviteSentRoom2: 'Attendee was invited to Room 2',
  callModeratorSentToast: 'Moderators have been notified.',
  callModeratorCooldownToast: 'Please wait before calling the moderators again.',
  requestingModeratorAssistance: 'is requesting moderator assistance.',
  // Icons
  unmuteIcon: `${baseBbbIcon}unmute`,
  listenOnlyIcon: `${baseBbbIcon}listen`,
  checkedIcon: `${baseBbbIcon}check`,

  // Polling
  pollQuestion: 'Are we good ?',
  answerMessage: 'All good!',
  questionSlideFileName: 'mockPollSlide.pdf',
  pollSidebarButton: 'div[data-test="pollSidebarButton"]',
  minimizePolling: 'button[data-test="minimizePolling"]',
  startPoll: 'button[data-test="startPoll"]',
  restartPoll: 'button[data-test="restartPoll"]',
  hidePollDesc: 'button[data-test="hidePollDesc"]',
  pollingContainer: 'aside[data-test="pollingContainer"]',
  pollLetterAlternatives: 'button[data-test="pollLetterAlternatives"]',
  pollOptionItem1: `${pollOptionItem}>>nth=0`,
  pollOptionItem2: `${pollOptionItem}>>nth=1`,
  pollOptionItem,
  anonymousPoll: 'input[data-test="anonymousPollBtn"]',
  publishPollingLabel: 'button[data-test="publishPollingLabel"]',
  pollAnswerOptionBtn: 'button[data-test="pollAnswerOption"]',
  receivedAnswer: 'td[data-test="receivedAnswer"]',
  quickPoll: 'button[data-test="quickPollBtn"]',
  pollQuestionArea: 'textarea[data-test="pollQuestionArea"]',
  userResponseBtn: 'button[data-test="userResponseBtn"]',
  pollAnswerOptionInput: 'input[data-test="pollAnswerOption"]',
  pollSubmitAnswer: 'button[data-test="submitAnswer"]',
  addPollItem: 'button[data-test="addPollItem"]',
  deletePollOption: 'button[data-test="deletePollOption"]',
  cancelPollBtn: 'button[data-test="cancelPollLabel"]',
  pollYesNoAbstentionBtn: 'button[data-test="pollYesNoAbstentionBtn"]',
  noPresentation: 'h4[data-test="noPresentation"]',
  autoOptioningPollBtn: 'input[data-test="autoOptioningPollBtn"]',
  currentPollQuestion: 'span[data-test="currentPollQuestion"]',
  allowMultiple: 'div[data-test="allowMultiple"] input[type="checkbox"]',
  firstPollAnswerDescOption: `${pollAnswerOptionDesc} input:nth-child(1)`,
  secondPollAnswerDescOption: `${pollAnswerOptionDesc}>>nth=1`,
  submitAnswersMultiple: 'button[data-test="submitAnswersMultiple"]',
  userVoteLiveResult: 'td[data-test="userVoteLiveResult"]',
  errorNoValueInput: 'div[data-test="errorNoValueInput"]',
  smartSlides1: 'smartSlidesPresentation.pdf',
  smartSlides2: 'SmartSlides.pdf',
  responsePollQuestion: 'div[data-test="pollQuestion"]',
  firstPollAnswerOptionBtn: `${pollAnswersOption}>>nth=0`,
  secondPollAnswerOptionBtn: `${pollAnswersOption}>>nth=1`,
  firstCheckboxInput: `${pollAnswersOption}`,
  yesNoOption: 'button[data-test="yesNoQuickPoll"]',
  yesNoAbstentionOption: 'li[role="menuitem"]>>nth=1',
  pollAnswerOptionD: 'button[data-test="pollAnswerOption"]>>nth=3',
  pollAnswerOptionE: 'button[data-test="pollAnswerOption"]>>nth=4',

  // Presentation
  currentSlideImg: '[id="whiteboard-element"] [class="tl-image"]',
  uploadPresentationFileName: 'uploadTest.png',
  presentationPPTX: 'BBB.pptx',
  presentationTXT: 'helloWorld.txt',
  startScreenSharing: 'button[data-test="startScreenShare"]',
  stopScreenSharing: 'button[data-test="stopScreenShare"]',
  managePresentations: 'div[data-test="managePresentations"]',
  presentationFileUpload: 'div#upload-modal input[type="file"]',
  presentationToolbarWrapper: 'div[id="presentationToolbarWrapper"]',
  nextSlide: 'button[data-test="nextSlide"]',
  prevSlide: 'button[data-test="prevSlide"]',
  skipSlide: 'select[data-test="skipSlide"]',
  presentationOptionsDownloadBtn: 'button[data-test="presentationOptionsDownload"]',
  confirmManagePresentation: 'button[data-test="confirmManagePresentation"]',
  presentationDownloadBtn: 'button[data-test="presentationDownload"]',
  presentationItem: 'div[data-test="presentationItem"]',
  removePresentation: 'button[data-test="removePresentation"]',
  presentationPlaceholder: 'div[data-test="presentationPlaceholder"]',
  presentationContainer: 'div[data-test="presentationContainer"]',
  minimizePresentation: 'button[data-test="minimizePresentation"]',
  restorePresentation: 'button[data-test="restorePresentation"]',
  shareExternalVideoBtn: 'div[data-test="shareExternalVideo"]',
  stopExternalVideoBtn: 'button[data-test="stopExternalVideoShare"]',
  videoModalInput: 'input[id="video-modal-input"]',
  startShareVideoBtn: 'button[data-test="startNewVideo"]',
  videoPlayer: 'div[data-test="videoPlayer"]',
  presentationTitle: 'h1[data-test="presentationTitle"]',
  fitToWidthButton: 'button[data-test="fitToWidthButton"]',
  presentationsList: 'div[id="upload-modal"] tbody',
  enableOriginalPresentationDownloadBtn: 'li[data-test="enableOriginalPresentationDownload"]',
  disableOriginalPresentationDownloadBtn: 'li[data-test="disableOriginalPresentationDownload"]',
  sendPresentationInCurrentStateBtn: 'li[data-test="sendCurrentStateDocument"]',
  downloadPresentation: 'div[data-test="downloadPresentationContainer"] > a',
  downloadPresentationToast: 'div[data-test="downloadPresentationToast"]',
  whiteboardOptionsButton: 'button[data-test="whiteboardOptionsButton"]',
  presentationFullscreen: 'li[data-test="presentationFullscreen"]',
  presentationSnapshot: 'li[data-test="presentationSnapshot"]',
  toolVisibility: 'li[data-test="toolVisibility"]',

  // YouTube frame
  youtubeLink: 'https://www.youtube.com/watch?v=Wjx5_IONaNg&t=158s&ab_channel=BigBlueButton',
  // The title we match for here is the title of the test video specified by youtubeLink
  youtubeFrame: 'div[data-test="videoPlayer"]',
  ytFrameTitle: 'a[class^="ytp-title-link"]',

  // Toasts
  statingUploadPresentationToast: 'To be uploaded ...',
  convertingPresentationFileToast: 'Converting file',
  defaultCurrentPresentationLabel: 'The current presentation is now',
  presentationPlaceholderLabel: 'There is no currently active presentation',
  noPresentationLabel: 'There is no currently active presentation',
  presentationDownloadEnabledLabel: 'You can now download the presentation',

  // Settings
  settingsSidebarButton: 'div[data-test="settingsSidebarButton"]',
  saveSettingsButton: 'button[data-test="saveSettingsButton"]',
  languageSelector: 'select[id="langSelector"]',
  messageTitle: 'h2[data-test="messageTitle"]',
  notesTitle: 'h2[data-test="notesTitle"]',
  dataSavingsTab: 'span[id="dataSaving"]',
  enableWebcamsToggleBtn: 'span[data-test="webcamToggleBtn"] input',
  enableDesktopSharingToggleBtn: 'span[data-test="desktopSharingToggleBtn"] input',
  shortcutsTab: 'span[id="shortcutsTab"]',

  // User
  userAvatar,
  moderatorAvatar: 'div[data-test="moderatorAvatar"]',
  viewerAvatar: 'div[data-test="viewerAvatar"]',
  userListItem: 'div[data-test="userListItem"]',
  usersListSidebarButton: 'div[data-test="usersListSidebarButton"]',
  toggleSidebarNavigation: 'button[data-test="toggleSidebarNavigation"], button[data-test="hasUnreadMessages"]',
  currentUser: 'div[data-test="userListItemCurrent"]',
  manageUsers: 'button[data-test="manageUsers"]',
  presenterClassName: 'presenter--',
  mobileUser: 'span[data-test="mobileUser"]',
  userNameSubs: 'span[data-test="userNameSubs"]',
  connectionStatusBtn: 'button[data-test="connectionStatusButton"]',
  connectionStatusModal: 'div[data-test="connectionStatusModal"]',
  copyStats: 'span[data-test="copyStats"]',
  dataSavingScreenshare: 'input[data-test="dataSavingScreenshare"]',
  screenshareLocked: 'button[data-test="screenshareLocked"]',
  connectionStatusItemEmpty: 'li[data-test="connectionStatusItemEmpty"]',
  connectionStatusTab2: 'li[id="react-tabs-2"]',
  connectionStatusItemUser: 'li[data-test="connectionStatusItemUser"]',
  connectionStatusLinkToSettings: `${networkDataContainer} span[role="button"]`,
  dataSavingWebcams: 'input[data-test="dataSavingWebcams"]',
  connectionStatusOfflineUser: 'div[data-test="offlineUser"]',
  videoUploadRateData: 'div[data-test="videoUploadRateData"]',
  connectionDataContainer: networkDataContainer,
  avatarsWrapperAvatar: 'div[data-test="avatarsWrapperAvatar"]',
  guestPolicyLabel: 'li[data-test="guestPolicyLabel"]',
  downloadUserNamesList: 'li[data-test="downloadUserNamesList"]',
  waitingUsersBtn: 'div[data-test="waitingUsersBtn"]',
  joinMeetingDemoPage: 'div[class^="join-meeting"]',
  askModerator: 'li[data-test="askModerator"]',
  alwaysAccept: 'li[data-test="alwaysAccept"]',
  alwaysDeny: 'li[data-test="alwaysDeny"]',
  deniedMessageElement: 'p[class="error-message"]',
  moreOptionsUserItemButton: 'div[data-test="moreOptionsUserItemButton"]',
  promoteToModerator: 'li[data-test="promoteToModerator"]',
  demoteToViewer: 'li[data-test="demoteToViewer"]',
  makePresenter: 'li[data-test="makePresenter"]',
  takePresenter: 'li[data-test="takePresenter"]',
  usersJoinMuted: 'li[data-test="usersJoinMuted"]',
  muteAllExceptPresenter: 'li[data-test="muteAllExceptPresenter"]',
  error403removedLabel: 'You have been removed from the meeting',
  removeUser: 'li[data-test="removeUser"]',
  removeUserConfirmationBtn: 'button[data-test="removeUserConfirmation"]',
  confirmationCheckbox: 'input[id="confirmationCheckbox"]',
  userBannedMessage1: 'div[id="app"] >> div >> div:nth-child(1)',
  userBannedMessage2: 'div[id="app"] >> div >> div:nth-child(2)',
  meetingEndedModalTitle: 'div[data-test="meetingEndedModal"]',
  unmuteUser: 'div[data-test="unmuteUser"]',
  ejectCamera: 'li[data-test="ejectCamera"]',
  closeUserList: 'button[data-test="closeUserList"]',
  userListPanel: 'div[data-test="userListPanel"]',
  clearStatus: 'li[data-test="clearStatus"]',

  // Lock Viewers
  lockViewersButton: 'button[data-test="lockViewersButton"]',
  unlockUserButton: 'li[data-test="unlockUserButton"]',
  applyLockSettings: 'button[data-test="applyLockSettings"]',
  guestPolicyTab: '[data-test="guestPolicyTab"]',
  guestPolicySelector: '[data-test="guestPolicySelector"]',
  participantPermissionsTab: '[data-test="participantPermissionsTab"]',
  presentationPermissionsTab: '[data-test="presentationPermissionsTab"]',
  presentationPolicySelector: '[data-test="presentationPolicySelector"]',
  presModeratorOnly: 'li[data-test="presModeratorOnly"]',
  presRequireApproval: 'li[data-test="presRequireApproval"]',
  presFreeForAll: 'li[data-test="presFreeForAll"]',
  takePresenterButton: 'button[data-test="takePresenterButton"]',
  requestPresenterButton: 'button[data-test="requestPresenterButton"]',
  waitingPresenterButton: 'button[data-test="waitingPresenterButton"]',
  approvePresenter: 'button[data-test="approvePresenter"]',
  denyPresenter: 'button[data-test="denyPresenter"]',
  lockShareWebcam: 'input[data-test="lockShareWebcam"]',
  lockSeeOtherViewersWebcam: 'input[data-test="lockSeeOtherViewersWebcam"]',
  lockShareMicrophone: 'input[data-test="lockShareMicrophone"]',
  lockPublicChat: 'input[data-test="lockPublicChat"]',
  lockPrivateChat: 'input[data-test="lockPrivateChat"]',
  lockEditSharedNotes: 'input[data-test="lockEditSharedNotes"]',
  lockUserList: 'input[data-test="lockUserList"]',
  hideViewersAnnotation: 'input[data-test="hideViewersAnnotation"]',
  hideViewersCursor: 'input[data-test="hideViewersCursor"]',
  lockScreenshare: 'input[data-test="lockScreenshare"]',
  hideViewersScreenshare: 'input[data-test="hideViewersScreenshare"]',
  screenshareActionsBtn: 'button[data-test="screenshareActionsBtn"]',
  screenshareShowAsContentBtn: 'li[data-test="screenshareShowAsContentBtn"]',
  screenshareMoveToThumbnailBtn: 'li[data-test="screenshareMoveToThumbnailBtn"]',
  selfScreenshareDockItem: '[data-test="selfScreenshareDockItem"]',
  whiteboardCursorIndicator: 'svg use[href="#cursor"]',

  // Locales
  locales: [
    'af',
    'ar',
    'az',
    'bg-BG',
    'bn',
    'ca',
    'cs-CZ',
    'da',
    'de',
    'dv',
    'el-GR',
    'en',
    'eo',
    'es',
    'es-419',
    'es-ES',
    'es-MX',
    'et',
    'eu',
    'fa-IR',
    'fi',
    'fr',
    'gl',
    'he',
    'hi-IN',
    'hr',
    'hu-HU',
    'hy',
    'id',
    'it-IT',
    'ja',
    'ka',
    'km',
    'kn',
    'ko-KR',
    'lo-LA',
    'lt-LT',
    'lv',
    'ml',
    'mn-MN',
    'nb-NO',
    'nl',
    'oc',
    'pl-PL',
    'pt',
    'pt-BR',
    'ro-RO',
    'ru',
    'sk-SK',
    'sl',
    'sr',
    'sv-SE',
    'ta',
    'te',
    'th',
    'tr-TR',
    'uk-UA',
    'vi-VN',
    'zh-CN',
    'zh-TW',
  ],

  // Webcam
  joinVideo: 'button[data-test="joinVideo"]',
  leaveVideo: 'button[data-test="leaveVideo"]',
  videoPreview: 'video[data-test="videoPreview"]',
  startSharingWebcam: 'button[data-test="startSharingWebcam"]',
  startCameraAsContent: 'button[data-test="StartCameraAsContent"]',
  closeIcon: 'svg[data-testid="CloseIcon"]',
  webcamConnecting: 'div[data-test="webcamConnecting"]',
  webcamContainer: 'video[data-test="videoContainer"]',
  webcamVideoItem: 'div[data-test="webcamVideoItem"]',
  videoDropdownMenu: 'button[data-test="videoDropdownMenu"]',
  advancedVideoSettingsBtn: 'li[data-test="advancedVideoSettingsButton"]',
  mirrorWebcamBtn: 'li[data-test="mirrorWebcamBtn"]',
  focusWebcamBtn: 'li[data-test="focusWebcamBtn"]',
  unfocusWebcamBtn: 'li[data-test="unfocusWebcamBtn"]',
  pinWebcamBtn: 'li[data-test="pinWebcamBtn"]',
  pinVideoButton: 'button[data-test="pinVideoButton"]',
  webcamsFullscreenButton: 'li[data-test="webcamsFullscreenButton"]',
  webcamSettingsTitle: 'span[id="webcam-settings-title"]',
  backgroundSettingsTitle: 'span[id="backgrounds-title"]',
  selectDefaultBackground: 'button[data-test="selectDefaultBackground"]',
  selectCustomBackground: 'button[data-test="selectCustomBackground"]',
  removeCustomBackground: 'button[data-test="removeCustomBackground"]',
  inputBackgroundButton: 'button[data-test="inputBackgroundButton"]',
  noneBackgroundButton: 'button[data-test="noneBackgroundButton"]',
  dropAreaBottom: 'div[data-test="dropArea-contentBottom"]',
  dropAreaLeft: 'div[data-test="dropArea-contentLeft"]',
  dropAreaRight: 'div[data-test="dropArea-contentRight"]',
  dropAreaTop: 'div[data-test="dropArea-contentTop"]',
  dropAreaSidebarBottom: 'div[data-test="dropArea-sidebarContentBottom"]',
  selfViewDisableBtn: 'li[data-test="selfViewDisableBtn"]',
  profileSidebarButton: 'div[data-test="profileSidebarButton"]',
  nextPageVideoPagination: 'button[data-test="nextPageVideoPaginationBtn"]',
  previousPageVideoPagination: 'button[data-test="previousPageVideoPaginationBtn"]',
  videoQualitySelector: 'select[id="setQuality"]',
  webcamItemTalkingUser: 'div[data-test="webcamItemTalkingUser"]',
  webcamSettingsModal: 'div[data-test="webcamSettingsModal"]',
  dropdownWebcamButton: 'div[data-test="dropdownWebcamButton"]',
  webcamMirroredVideoPreview: 'video[data-test="mirroredVideoPreview"]',
  resizeWebcamHandler: 'div#cameraDock + div > div[style*="user-select: none"]',

  // Whiteboard
  whiteboard: 'div[data-testid="canvas"]',
  wbLayer: 'div[data-testid="layer"]',
  wbToolbar: 'div[class^="tlui-toolbar__tools tlui-toolbar__tools__mobile"]',
  wbShapesButton: 'button[data-testid="tools.more"]',
  wbHandButton: 'button[data-testid="tools.hand"]',
  wbRectangleShape: 'button[data-testid$=".rectangle"]',
  wbEllipseShape: 'button[data-testid="tools.more.ellipse"]',
  wbTriangleShape: 'button[data-testid="tools.more.triangle"]',
  wbLineShape: 'button[data-testid="tools.more.line"]',
  wbPencilShape: 'button[data-testid="tools.draw"]',
  wbStickyNoteShape: 'button[data-testid="tools.note"]',
  wbTextShape: 'button[data-testid$=".text"]',
  wbTypedText: 'div[data-shape="text"]',
  wbTypedStickyNote: 'div[data-shape-type="note"]',
  wbDrawnShape: 'div[data-shape-type="geo"]',
  wbDraw: 'div[data-shape-type="draw"]',
  wbPollShape: 'div[data-shape-type="poll"]',
  wbDrawnLine: 'div[data-shape-type="line"]',
  multiUsersWhiteboardOn: 'button[data-test="turnMultiUsersWhiteboardOn"]',
  multiUsersWhiteboardOff: 'button[data-test="turnMultiUsersWhiteboardOff"]',
  whiteboardViewBox: 'svg g[clip-path="url(#viewBox)"]',
  changeWhiteboardAccess: 'div[data-test="changeWhiteboardAccessUser"]',
  pencil: 'button[data-test="pencilTool"]',
  resetZoomButton: 'button[data-test="resetZoomButton"]',
  zoomInButton: 'button[data-test="zoomInBtn"]',
  zoomOutButton: 'button[data-test="zoomOutBtn"]',
  wbEraser: 'button[data-testid="tools.eraser"]',
  wbArrowShape: 'button[data-testid="tools.arrow"]',
  wbUndo: 'button[data-testid="main.undo"]',
  wbRedo: 'button[data-testid="main.redo"]',
  whiteboardStyles: 'button[data-testid="mobile.styles"]',
  wbColorRed: 'button[data-id="red"]',
  wbFillDrawing: 'button[data-testid="style.fill.solid"]',
  wbDashDotted: 'button[data-testid="style.dash.dotted"]',
  wbSizeLarge: 'button[data-testid="style.size.l"]',
  wbOptions: 'button[data-testid="main.action-menu"]',
  wbDuplicate: 'span[id="TD-Tools-Copy"]',
  wbRotate: 'button[data-testid="menu-item.rotate-cw"]',
  wbMoveBackward: 'button[data-testid="menu-item.send-backward"]',
  wbMoveForward: 'button[data-testid="menu-item.bring-forward"]',
  wbMoveToFront: 'button[data-testid="menu-item.bring-to-front"]',
  wbPaste: 'button[data-testid="menu-item.paste"]',
  wbTextTrue: 'div[data-hastext="true"]',
  wbDrawnArrow: 'div[data-shape-type="arrow"]',
  wbAutoHideToggleBtn: 'input[data-test="whiteboardToolbarAutoHideToggleBtn"]',
  turnInfiniteWhiteboardOn: 'button[data-test="turnInfiniteWhiteboardOn"]',

  // About modal
  aboutTabButton: 'li[data-test="aboutTabButton"]',
  aboutModal: 'div[data-test="aboutModalTitleLabel"]',

  // Help button
  helpLinkButton: 'a[data-test="helpLinkButton"]',
  helpPageTitle: 'BigBlueButton Tutorials | Built For Teachers | BigBlueButton',

  // Dark mode
  darkModeToggleBtn: 'input[data-test="darkModeToggleBtn"]',
  actionsBarBackground: 'section[id="ActionsBar"]',
  navbarBackground: 'header[id="Navbar"]',
  fullscreenModal: 'div[id="fsmodal"]',
  sharedNotesBackground: 'div[data-test="notes"]',

  // Layout management
  manageLayoutBtn: 'li[data-test="manageLayoutBtn"]',
  focusOnPresentation: 'button[data-test="presentationFocusLayout"]',
  focusOnVideo: 'button[data-test="videoFocusLayout"]',
  smartLayout: 'button[data-test="smartLayout"]',
  customLayout: 'button[data-test="customLayout"]',
  updateLayoutBtn: 'button[data-test="updateLayoutBtn"]',
  updateEveryoneLayoutToggle: 'input[data-test="updateEveryoneLayoutToggle"]',
  cameraDock: 'div#cameraDock',

  // Font size
  increaseFontSize: 'button[data-test="increaseFontSize"]',
  decreaseFontSize: 'button[data-test="decreaseFontSize"]',

  // Learning dashboard
  learningDashboardSidebarButton: 'div[data-test="learningDashboardSidebarButton"]',
  panels: 'div[role="tablist"]',
  messageLearningDashboard: 'td[data-test="userTotalMessagesDashboard"]',
  userOnlineTime: 'td[data-test="userOnlineTimeDashboard"]',
  pollTrueFalse: 'button[data-test="pollTrueFalse"]',
  pollPanel: 'button[data-test="pollsPanelDashboard"]',
  pollTrueFalseQuestion: 'div[role="rowgroup"] div:nth-child(3) div',
  pollTrueFalseAnswer: 'div[role="cell"]:nth-child(3)',
  pollABCDQuestion: 'div[role="rowgroup"] div:nth-child(4) div',
  pollABCDAnswer: 'div[role="cell"]:nth-child(4)',
  pollYesNoQuestion: 'div[role="rowgroup"] div:nth-child(5) div',
  pollYesNoAnswer: 'div[role="cell"]:nth-child(5)',
  pollUserResponseQuestion: 'div[role="rowgroup"] div:nth-child(6) div',
  pollUserResponseAnswer: 'div[role="cell"]:nth-child(6)',
  pollTotal: 'div[role="cell"]:nth-child(2)',
  meetingStatusActiveDashboard: 'span[data-test="meetingStatusActiveDashboard"]',
  meetingDurationTimeDashboard: 'p[data-test="meetingDurationTimeDashboard"]',
  userNameDashboard: 'td[data-test="userLabelDashboard"] button',
  userWebcamTimeDashboard: 'td[data-test="userWebcamTimeDashboard"]',
  userRaiseHandDashboard: 'td[data-test="userRaiseHandDashboard"]',
  userStatusDashboard: 'td[data-test="userStatusDashboard"]',
  userActivityScoreDashboard: 'td[data-test="userActivityScoreDashboard"]',
  activityScorePanelDashboard: 'button[data-test="activityScorePanelDashboard"]',
  downloadSessionLearningDashboard: 'button[data-test="downloadSessionDataDashboard"]',
};

// Recording playback
const topBar: string = 'div.top-bar';
const videoControlBar: string = 'div.vjs-control-bar';
export const playbackElements = {
  sectionLeftButton: `${topBar} .left button`,
  toggleThemeButton: `${topBar} .right button[aria-label="Toggle theme"]`,
  searchButton: `${topBar} .right button[aria-label="Search"]`,
  swapContentButton: `${topBar} .right button[aria-label="Swap content"]`,
  topBar,
  title: `${topBar} .center span.title`,
  mediaArea: 'div.media',
  applicationArea: 'div.application',
  topContentArea: 'div.top-content',
  bottomContentArea: 'div.bottom-content',
  chatContentArea: 'div#chat',
  applicationControlButton: 'div.application-control div',
  notesContentArea: 'div#notes',
  videoControlBar,
  playPauseButton: `${videoControlBar} button.vjs-play-control`,
  seekBackButton: `${videoControlBar} button.vjs-seek-button.skip-back`,
  seekForwardButton: `${videoControlBar} button.vjs-seek-button.skip-forward`,
  progressBar: `${videoControlBar} div.vjs-play-progress`,
} as const;
