server:
  listen_host: 127.0.0.1
  listen_port: 8378
  #max of concurrent connections
  max_connections: 500
  max_connections_per_session_token: 3
  #rate limit
  max_connections_per_second: 100
  # If you are running a cluster proxy setup, you need to allow the url of the Frontend
  # Add an Authorized Cross Origin. See https://docs.bigbluebutton.org/administration/cluster-proxy
  #authorized_cross_origin: 'bbb-proxy.example.com'
  json_patch_disabled: false
  subscriptions_allowed_list:
  subscriptions_denied_list:
redis:
  host: 127.0.0.1
  port: 6379
  password: ""
hasura:
  url: ws://127.0.0.1:8085/v1/graphql
graphql-actions:
  url: http://127.0.0.1:8093
auth_hook:
  url: http://127.0.0.1:8090/bigbluebutton/connection/checkGraphqlAuthorization
session_vars_hook:
  url: http://127.0.0.1:8901/userInfo
prometheus_advanced_metrics_enabled: false
log_level: INFO
