exports.manageUsers = 'button[data-test="manageUsers"]';
exports.createBreakoutRooms = '[data-test="createBreakoutRooms"]';
exports.inviteBreakoutRooms = '[data-test="inviteBreakoutRooms"]';
exports.randomlyAssign = '[data-test="randomlyAssign"]';
exports.modalConfirmButton = '[data-test="modalConfirmButton"]';
exports.breakoutRemainingTime = '[data-test="breakoutRemainingTime"]';
exports.breakoutRoomsItem = '[data-test="breakoutRoomsItem"]';
exports.alreadyConnected = 'span[class^="alreadyConnected--"]';
exports.breakoutJoin = '[data-test="breakoutJoin"]';
exports.userJoined = 'div[aria-label^="Moderator3"]';
exports.breakoutRoomsButton = 'div[aria-label="Breakout Rooms"]';
exports.joinRoom1 = 'button[aria-label="Join room 1"]';
exports.chatButton = 'div[data-test="chatButton"]';
