CREATE TABLE documents (
  name VARCHAR(255) PRIMARY KEY,
  content BYTEA NOT NULL,
  updated_at TIMESTAMP DEFAULT NOW(),
  ended_at TIMESTAMP
);

GRANT USAGE ON SCHEMA public TO blocknote_app;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER
ON ALL TABLES IN SCHEMA public
TO blocknote_app;
