name: Build all docker images

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"

jobs:
  html5-client:
    uses: ./.github/workflows/build-docker-image.yml
    with:
      image_name: "html5-client"

  learning-dashboard:
    uses: ./.github/workflows/build-docker-image.yml
    with:
      image_name: "learning-dashboard"

  graphql-actions:
    uses: ./.github/workflows/build-docker-image.yml
    with:
      image_name: "graphql-actions"

  graphql-middleware:
    uses: ./.github/workflows/build-docker-image.yml
    with:
      image_name: "graphql-middleware"

  graphql-server:
    uses: ./.github/workflows/build-docker-image.yml
    with:
      image_name: "graphql-server"

  export-annotations:
    uses: ./.github/workflows/build-docker-image.yml
    with:
      image_name: "export-annotations"

  bbb-etherpad:
    uses: ./.github/workflows/build-docker-image.yml
    with:
      image_name: "bbb-etherpad"

  akka-bbb-apps:
    uses: ./.github/workflows/build-docker-image.yml
    with:
      image_name: "akka-bbb-apps"