name: CI Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"

jobs:
  html5-client:
    uses: ./.github/workflows/build-docker-image.yml
    with:
      image_name: "html5-client"
      docker_context: "./bigbluebutton-html5"

  learning-dashboard:
    uses: ./.github/workflows/build-docker-image.yml
    with:
      image_name: "learning-dashboard"
      docker_context: "./bbb-learning-dashboard"

  graphql-actions:
    uses: ./.github/workflows/build-docker-image.yml
    with:
      image_name: "graphql-actions"
      docker_context: "./bbb-graphql-actions"

  graphql-middleware:
    uses: ./.github/workflows/build-docker-image.yml
    with:
      image_name: "graphql-middleware"
      docker_context: "./bbb-graphql-middleware"

  graphql-server:
    uses: ./.github/workflows/build-docker-image.yml
    with:
      image_name: "graphql-server"
      docker_context: "./bbb-graphql-server"

  export-annotations:
    uses: ./.github/workflows/build-docker-image.yml
    with:
      image_name: "export-annotations"
      docker_context: "./bbb-export-annotations"
